js/store.js

This is the different-way-to-do-Promises that I mentioned a few days ago.
I'll go through line-by-line explaining what I'm changing.
**+-449:** Added a .catch() handler. In the event of a network error, the promise would have rejected and thrown an exception ("Uncaught rejection"). This just logs it to console.
**+515:** `async` keyword forces the function to return a `Promise`, so `return false;` is effectively `return Promise.resolve(false);` without the extra verbiage.
**-517:** As a general guideline, if you're creating a `Promise` to handle the result of another `Promise` you can chain them, which is what +533 does.
**+540:** Since we're returning the promise returned from this `.then()`, the value stored in the resolved `Promise` back in `AppPageClass.data` will be the value we …

Streamline promises in store.js

---

manifest.json

[*:// == (http|https)://](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns#scheme)
Fixes the missing 's' from es.isthereanydeal.com

Add community to manifest permissions

---

js/common.js

I've tested this on an old portable install of FF 56 dev edition and Waterfox.
Options load and save. I didn't notice any missing Store page features.
There are a bunch of promise rejections that I'm going to try to track down. Unfortunately they look like this in the console:
`uncaught exception: undefined (unknown)`
Resolves tfedor/Enhanced_Steam#7

Shim for Promise.finally() on FF <58

---

js/options.js

Noticed this error in FF browser console. Not sure if the "blur" event on the window happens in Chrome as well?

Sanity check e.target in saveOptionFromEvent()

---

js/common.js

There are currently 13x `img/overlay/early_access_banner_language.png` and 25x possible languages in Language.languages.
Should getCurrentSteamLanguage() always be lowercase?
Resolves tfedor/Enhanced_Steam#12

Global language has been replaced with Language.getCurrentSteamLanguage()

---

js/common.js

`node.querySelector('.es_progress_error')` would always fail, so `nodeError === null` on 425, which throws.
Alternately 413 can be `nodeError = node.nextElementSibling` and 414 `if (!nodeError || !nodeError.matches('.es_progress_error'))`

Progress bar error message handling was erroring.

---

js/store.js

On the https://store.steampowered.com/account/registerkey page, succeed or fail the response was "wait 30 minutes and try again"

Register multiple keys always had the default error

---

js/store.js

An example: https://store.steampowered.com/app/482400/System_Shock/
AppPageClass.data.charts.chart would be either `[]` or `{ 'current': #, 'peaktoday': #, 'peakall': # }` depending on if the chart has information.

Games that don't have a SteamChart (yet) threw

---

js/store.js

HD button handler was exiting early because the plain javascript equivalent of `$().on(event, filter, handler)` is more complicated than it should be.

Fixes error when video should start playing and didn't, also makes the HD button function

---

js/common.js

"undefined" doesn't round-trip to JSON, so the bug that required tfedor/Enhanced_Steam#31 to patch can cause `LocalData.get('playback_hd')` to throw

Catch JSON errors in LocalData

---

js/store.js

Removing the event handlers after the row is added to the page didn't cause them to be removed in Chrome. In Firefox they were removed and not replaced, causing the hover popup to stop appearing after the first page.

Not sure why the event handlers needed to be removed, and this didn't remove them in Chrome

---

js/common.js

The extension crashed if the "About" menu item, which seems to only appear on certain clients, wasn't found
See #44 for detailed explanation

Fixed crash with "Hide 'About' link"

---

css/options.css

When scrolling down the options the nav bar will stay at the left.
See #68

Make nav bar sticky

---

js/common.js

This restores the Early Access banner on Community Hubs.

EarlyAccess.checkNodes() expects a sequence of selectors

---

js/community.js
js/options.js

The custom profile didn't save because `saveOption` didn't specify a key

Save custom profile

---

js/common.js

Localization now works on both Steam pages and the options page, with the exception that the user has to visit any Steam site first.

Localization

---

css/enhancedsteam.css
js/common.js
js/store.js

Steam recently expanded curator pages to also be used by developers, publishers and as a per-app dlc overview.
Examples:
https://store.steampowered.com/curator/11247776-Co-op-Cowboys/
https://store.steampowered.com/developer/DevolverDigital/
https://store.steampowered.com/publisher/2K/
https://store.steampowered.com/publisher/2K/list/35241
https://store.steampowered.com/dlc/548430/Deep_Rock_Galactic/
The page structure for all of these is almost identical.

Add Highlighting to Curator pages

---

js/common.js

https://developer.chrome.com/extensions/extension#method-getURL

chrome.extension.getURL is deprecated

---

js/content/community.js

Previously the constructor couldn't get found because it was `async`

Fix custom profile

---

js/content/store.js

Some games (e.g. 201270, 201271) have different appid in store page and community witch cause some links in app page broken.

Fix different appid in store page and community

---

css/enhancedsteam.css

The buttons just showed the default icon.
Also the steam favicon is unfortunately not compatible. I don't know if the steam icon can be included in this repo so I just grabbed the best url I could find.

Fix icons on store page link buttons

---

js/content/common.js

As it seems, `g_rgWalletInfo` can either be `undefined` or `null`

Check g_rgWalletInfo for null

---

js/core.js

Setting it to `null` is fine, since the function that uses this settings, does a null-check.
Removes warning in console about unrecognized key

Set default for homepage_tab_last

---

css/enhancedsteam.css
js/content/store.js
js/core.js
localization/de/strings.json
localization/en/strings.json
options.html

ProtonDB is a website for user submitted compatibility reports for Valve's Steam Play/Proton for Linux.

Add support for ProtonDB links to store page

---

js/content/common.js
js/content/store.js

Notably, this is only the first half of solving the issue. Uncaught errors in the background context aren't handled correctly.
Upgrading the background context error handling to return valid and useful errors to display in the ProgressBar is the other half of the solution.

Upgrade ProgressBar to more accurately reflect requests in progress

---

js/content/community.js

The parameter `start` is not meant to be a page number.
Instead it should be the [index of the item, where you want to start the query](https://steamcommunity.com/groups/enhancedsteam/discussions/0/622954747302765282/#c622954747303181753).

Fix market stats

---

css/enhancedsteam.css

Resolves tfedor/AugmentedSteam#192
The margin increase slid the images to the right, outside of their box. In older versions of Firefox, the image was replaced by an ellipsis. In newer versions, a stripe of highlighting appears on the left and the right edge of the image is cut off.

Fit popular tags images in their bounding boxes

---

css/enhancedsteam-firefox.css
css/enhancedsteam.css

Resolves tfedor/AugmentedSteam#186.
I'm not sure why the `!important`  directives are attached to the `.es_overlay` classes? We may want to remove them from the `develop` branch as well.

Limit Early Access banner width

---

css/enhancedsteam.css
js/content/common.js
js/content/community.js
js/content/store.js
js/core.js

- Highlight items
- [search box](https://github.com/tfedor/AugmentedSteam/issues/164#issuecomment-477448344)
- genre pages
- the whole front page
- curator pages
- "/tag/browse/"
- Outline elements without a background
- Fix highlighting on search page
- Round corners for highlights on activity page
- Fix #222 
- Fix weird positioning of "Compare" stats button on profile activity page
- Fix comparing stats on profile activity page to oneself
- New default color for wishlisted games
Previously:
Now:

Highlights

---

js/content/store.js

`null` or `undefined` user notes resulted in crashing the whole app page

Assign empty object to notes if "user_notes" are undefined or null

---

css/enhancedsteam.css
js/content/community.js

Fix overlapping of sold amount in last 24 hours with native Steam item summary

---

css/enhancedsteam.css
js/content/common.js
js/content/community.js
js/content/store.js
js/core.js
localization/en/strings.json
localization/zh-CN/strings.json
localization/zh-TW/strings.json
options.html

Depends on #231 
- Adjusts the style of the filter elements on the search page to the native Steam ones
- Fix placeholder of price input (respect the currency's decimal separator)
- Give a hint on how the input for the price is expected to look like (e.g. 0,00 for EUR)
- Remove "See all" expander (this just hid some very useful features of AS imo)
- Respect user state when displaying filters (owned, wishlisted, ignored filters are hidden when logged out)
- Fix for the "Update note" button always shown as active
- Hide user notes button on app page when user has already disabled them on their wishlist
- And finally, stop saving the states of the filters (en- or disabled) in `SyncedStorage`, instead save that in the query string like the native filters also do

Filter elements

---

css/options.css
options.html

This allows users to use HTML5's number arrows to increase and decrease. It also provides a more user-friendly way for mobile users.

Feature number input

---

img/profile_styles/blue/style.css
img/profile_styles/green/style.css
img/profile_styles/grey/style.css
img/profile_styles/orange/style.css
img/profile_styles/pink/style.css
img/profile_styles/purple/style.css
img/profile_styles/red/style.css
img/profile_styles/teal/style.css
img/profile_styles/yellow/style.css

All coloured profiles now have a properly-coloured border for the 'Add a Showcase' box. Grey theme was also missing its text colour on showcase names, and Blue theme's 'Add a Showcase' looked slightly odd with the default gradient still on the side.

Added some missing profile colour elements

---

js/content/community.js

Resolves https://github.com/tfedor/AugmentedSteam/issues/396
Resolves https://github.com/tfedor/AugmentedSteam/issues/138
I found that this feature was part of ES a long time ago. In particular this commit: https://github.com/jshackles/Enhanced_Steam/commit/dd0873a86962901b3fa757c63ce69180986e4a7e
I don't know why it was removed later, but the locale remained present throughout everything.

Added nickname any user

---

css/enhancedsteam.css
js/content/store.js

Function from those which Valve should implement by themselfs long ago. Personally I use this feature for about 2 years now (as self-written userscript) and cannot imagine Steam-shoping without this. Because how else you can checkout how these games will look like at your own screen? Well, to be honest Steam client's Big Pucture can show store screenshots at fullscreen. But we are advanced users who use all those advanced functions in browser and we need those screenshots at fullscreen right here right now. There they are, right in this pull request.
_Wow! Felt like a marketer by writing this._
- No redudant JS code included!
Contained JS is necesarily only for including needed buttons and activating browsers built-in fullscreen mode. Whole hard work with images is done by native Steam's …

Add fullscreen screenshot view at app pages

---

manifest.json

the former is incompatible with the extension and causes console errors, the latter is used on third-party logins through Steam

exclude translation.steampowered.com steamcommunity/openid in the manifest

---

localization/en/strings.json

should've already been removed in 3a4d0f299d2395a131aa6784a6b09e3f00ca07ad

remove "showclient" from en strings

---

js/options/options.js

fixes #208
I have no idea why this works but it does for me.
Steps I used to test the issue:
1. Log out of Steam
2. From the home page, change Steam language to `Traditional Chinese` OR `Simplified Chinese`
3. Open AS Settings, an option for `SteamRepCN` should appear
4. Change to other languages, and the `SteamRepCN` option should disappear

another attempt at fixing SteamRepCN option

---

options.html

"Simplified" and "Traditional" (Chinese) is already provided in the translated text in brackets.

remove redundant information from warning_language

---

js/content/community.js

Some steam groups  post links to the steam pages, but also apply a card image to the link itself.
In the code here script update only links, that don't have any children elements, so this links will not be parsed. Here I made sure, that this kind of links will be valid. Although I am not sure why validation by the nodes exists. What will break, if it's removed completely?
Example page to track in community:
https://steamcommunity.com/groups/IndieBundleTracker#announcements/detail/3326392068396183880

Add support for community steam links that apply cards images to the link tag

---

js/content/store.js

Some fixes regarding DLC checkboxes:
1. Clicking "Select Unowned DLC" etc. under Options doesn't toggle the "add items to cart" button
2. Selecting and deselecting the checkboxes multiple times will cause items to fail to add to cart
3. Switch to using the larger arrow icons from addReviewToggleButton()

fix dlc checkboxes

---

css/enhancedsteam.css

checkbox image is missing on firefox for some reason...

fix missing checkbox image on firefox

---

js/content/store.js

Regarding false positives, after checking a few games, I think those are typically bundles or packages and will display the blue info button, so instead of adding more checks we can just check for that. Although this does mean `addPackBreakdown()` has to be ran before `addPackageInfoButton()`.

fix pack breakdown prices

---

js/content/store.js

Fix #537 
This style was not present in ES, and I'm not sure what it's supposed to fix, but it seems to be the cause of the issue.
ES had the following styles, but I'm not sure what they are for either:
`$(".home_page_body_ctn:first").css("min-height", "400px");`
`$(".has_takeover").css("min-height", "600px");`

Fix horizontal scrollbar on homepage

---

js/content/community.js

Resolves #553, needs more testing though.
Some notes:
1. The language tags are applied as listed in the LANGUAGE dropdown under FILTER BY CATEGORY, which differs from the values retrieved by `Language.getCurrentSteamLanguage();`
2. For the links in the BROWSE BY section, I found that if you remove the language tag from `href` or `onclick` or remove the attribute `onclick`, the links will sometimes require multiple clicks to work (especially on FireFox), and the user language tag can sometimes get added back after navigating multiple times. Setting the language tag here to `-1` (none specified) works better. I left the old code in comments for testing.

improve "Don't automatically filter guides by user language" option

---

css/enhancedsteam.css
js/content/store.js

Make it so that the "on price mouseover" behaviour is actually on the prices, instead of extending to the purchase button and discount %.

Improve regional price mouseover behaviour

---

js/content/store.js

1. Used `continue` in the `for of` loop, else it will exit too early.
2. Simplified some stuff and added support for a handful of products that don't have "pack" in the title. Some store pages for testing:
https://store.steampowered.com/app/245170/Skullgirls/
https://store.steampowered.com/app/910490/Killsquad/
https://store.steampowered.com/app/322330/Dont_Starve_Together/
https://store.steampowered.com/app/246920/Bombernauts/
I thought about adding "double pack" as mentioned in https://github.com/tfedor/AugmentedSteam/pull/592#issuecomment-544701459, but the number of supported products is about the same as false positives ([example](https://store.steampowered.com/app/37400/Time_Gentlemen_Please_and_Ben_There_Dan_That_Special_Edition__Double_Pack/)) so I don't think it's worth it.

Further improve pack breakdown prices

---

manifest.json

Loading this page made AS crash, because it couldn't find the global menu element. I could add a check for that, but I don't think any code in AS is meant for the chat, so I guess it's better to exclude it.

Exclude "*://steamcommunity.com/chat/*" in manifest

---

js/content/store.js

After adding dev/pub homepage links, the text sometimes overflows and remains hidden. Fix this by adding the "+" button implemented by Steam.
Store pages for testing:
https://store.steampowered.com/app/289070/Sid_Meiers_Civilization_VI/
https://store.steampowered.com/app/845880/Touhou_Scarlet_Curiosity/

Fix devpub text overflow hidden

---

js/content/community.js

AS would produce a lot of errors, if a profile did not exist. This fixes that.

Added error message check for user profiles

---

localization/en/strings.json

This was removed in https://github.com/tfedor/AugmentedSteam/commit/5cb99e3e342b2b4a47e261d6a21e785b2de76d31, but it's still used:
https://github.com/tfedor/AugmentedSteam/blob/bc096d5bd26717cbba74789646805d9aaba45940/js/content/community.js#L2706

Restore missing translation string "lowest_price"

---

css/enhancedsteam.css
js/content/common.js

Fix #620
You may need to activate some options under "Tag" to trigger the issue.
The original fix was to add checks for discounted prices, but for the top highlight section I found there're several different styles:
https://store.steampowered.com/recommended/morelike/app/1016960/
https://store.steampowered.com/recommended/friendactivity/
https://store.steampowered.com/recommended/
So I made the tags appear right above the title instead, which covers all cases above.
Example of default style on owned games:

Fix recommended page highlight

---

css/enhancedsteam.css
js/content/community.js

Resolves #681 and fixes the option not working after inputting search terms.

Remove duplicate filter options on "All Games" page

---

js/background/background.js
js/content/common.js
js/content/community.js
js/content/store.js

1. Make it so that this option will show achievements for the profile you're currently viewing, instead of only showing your achievements on the games you own.
2. Minor refactoring.

Improve "Show achievement stats on All Games page" option

---

js/content/store.js

Fix https://github.com/tfedor/AugmentedSteam/issues/674#issuecomment-560113211
Apps don't necessarily have a franchise row, so the last row could be a publisher row.
Also removed unnecessary check as mentioned in https://github.com/tfedor/AugmentedSteam/pull/655#discussion_r349700371

Improve fix for franchise row search links

---

css/enhancedsteam.css
js/content/store.js

Resolves #361 by copying the text from a DRM notice that contains "DRM" or "...account (Supports Linking to Steam Account)" and placing it in the warning box. Ideally it should be made to extract the custom text provided by devs, but I feel it's too much work for what it's worth.
Also added EA Origin & Xbox Live detection.

Improve drm warnings

---

css/enhancedsteam.css
js/content/community.js

If getting images to load is as simple as https://github.com/tfedor/AugmentedSteam/commit/01e9d69bab059fdfe92eab48ff8cd64c2fecb029 , I think we can consider hiding Steam's option instead, since as mentioned in https://github.com/tfedor/AugmentedSteam/issues/681#issuecomment-564059216 our option does have the advantage of not refreshing the page.
Additionally, https://github.com/tfedor/AugmentedSteam/commit/01e9d69bab059fdfe92eab48ff8cd64c2fecb029 should be applied when hiding uncommon games instead, because that's when games further down with unloaded images potentially get shown.

Restore AS's filter option on "All Games" page

---

js/content/store.js
localization/en/strings.json

1. Add some new homepage sections to the customizer. For Steam Labs Recommendations, the option hides all experiments, but I guess it can be set up to hide individual experiments as well if there is demand.
2. Fixed "Updates and Offers" & "Games Streaming Now" options not showing. The sections turns visible only after you scroll further down.
3. Simplify the customizer code a bit.
4. ~~Remove addDynamic method since all current options are already manually added. IMO it's better to manually add options and check if they work properly when new ones pop up.~~
Fixed and simplified addDynamic method. I suppose it can be useful for sale events.

Improve homepage customizer options

---

js/content/common.js

Also prevents errors on e.g. workshop items which don't have left/right controls.

Simplify apppage horizontal scrolling

---

js/content/common.js

Regression from e8eed7a59f69d6474a3c1f2ca952ac30b10ec9cc
`document.querySelector(".apphub_AppName")` can be `null` on sub/bundle pages

Fix error on sub/bundle pages

---

js/content/community.js

Accidently removed in 41c7c2329409588dbcf368dec1ad54d9a1a4a2fe.

Fix custom links spacing

---

js/content/common.js
js/content/store.js

Styles for the loading wrapper have been moved to https://steamstore-a.akamaihd.net/public/shared/css/shared_global.css, so inserting home.css on search pages doesn't seem to be doing anything apart from making the page look noticeably brighter. Should be safe to remove.

Remove inserting home.css

---

js/content/store.js

Valve is starting to outright hide bundles/dlcs that users have excluded by preference instead of blurring them.
Store page to test the issue (with default preferences enabled): https://store.steampowered.com/app/1126290/Lost/

Fix apppage errors

---

localization/en/strings.json

inadvertently removed in https://github.com/tfedor/AugmentedSteam/commit/5fa8f98aaa5d96c969fe6e9aeab3fb6b8adf2f1c#diff-7d69fd78b2194316dd711ae035f6e13c

Restore localization key help_translate

---

js/content/common.js

Prevent spotlight elements from being selected in horizontalScrolling()

---

css/enhancedsteam.css
js/content/community.js

Closes #670 
Some problems:
1. `getAppStatus()` takes a while to get updated app status, so the wrong button may be shown
2. `User.isSignedIn` only checks if the user is logged in based on the current page (in this case steamcommunity), but the user needs to be logged in to steamstore for this feature to work
Also need some ideas on how to style the text that shows in case of failure.

Add remove from wishlist button to community hub

---

js/content/store.js

Also removed unused TagPageClass.
I've checked each expression.
I'm aware they sometimes allow seemingly incorrect paths, however this is because steam also allows this.
For example:
https://store.steampowered.com/steamaccount/addfundskjdsakjdsakjkjsa

Fixed several store url path RegExps

---

js/content/store.js

This prevents the "homepagesidebar" option from showing up during sale events, since enabling it only overlaps and clutters the homepage.

Fix "homepagesidebar" option in customizer

---

js/content/common.js

I'm not sure what these default values are for, but it seems to work fine without them and also prevents executing `_processBundles()` on wishlist entries (which can lead to errors if the app happens to be in a live bundle).

Fix default values for priceCallback and bundleCallback

---

js/content/store.js

Closes #713
Okay, so stupid me didn't see #826 by @candela97 until I finished writing my PR.
I'm still opening this PR, because my solution is a bit different.
It directly uses Steam's formatting instead.
It also adds base price variables.
My solution assigns `false` to price, if no price exists (item not on sale), instead of price of 0.

Add additional data to exported wishlist (Alternative)

---

js/content/community.js
js/core.js

Replaces an oldNode with a newNode. Can be used instead of having to insert a newNode next to an oldNode, then removing the oldNode.

Create HTML.replace() method

---

css/enhancedsteam.css
js/content/store.js
localization/en/strings.json

Alternative to #830
Includes the changes and suggestions in the previous PR, also moved a part of the giftcard text to the tooltip, because it might get too long:

Simplify addCustomMoneyAmount()

---

js/content/store.js

This fixes `Uncaught TypeError: rows is not iterable` when using the review count filter.

Default value for rows in applyCountFilter

---

js/core.js

1. A selector string should be allowed for the first argument, reverts https://github.com/tfedor/AugmentedSteam/commit/d43cceffa5024a099405c01c61cb983a1fbae515.
2. Use `outerHTML` to replace elements

Fix HTML scripts

---

js/background/background.js

This ensures the user's steamID is available regardless of whether the user is logged in to their profile or not, so as to not disable Store features (e.g. wishlist remove) that only require logging in to the Store.

Use a surefire way to retrieve steamID

---

css/enhancedsteam.css
js/content/community.js

Make use of the Intersection Observer API for better performance, available since Firefox 53 (behind a preference) and enabled for all since Firefox 55.

Refactor addGamelistAchievements()

---

src/css/augmentedsteam.css
src/js/Content/Features/Community/MarketListing/CMarketListing.js
src/js/Content/Features/Community/MarketListing/FBackgroundPreviewLink.js
src/js/Content/Features/Community/MarketListing/FBadgePageLink.js
src/js/Content/Features/Community/MarketListing/FSoldAmountLastDay.js

1. Restore displaying sold amount info as done by ES -- also appears above the "Median Sale Prices" graph and "Listings" title for commodities like https://steamcommunity.com/market/listings/264710/Planet%204546B%20Postcard
2. Add sign-in check for addBackgroundPreviewLink()

Simplify MarketListingPageClass

---

src/js/Content/Modules/AugmentedSteam.js

Should close #930
`#account_pulldown` has been displaying community names for a while now, and the only reference to account names left is in the logout link text and page header, so adjust the feature accordingly.
Also limit the replacement of page header text to account related pages, see https://github.com/tfedor/AugmentedSteam/issues/930#issuecomment-739534849. Account names are also displayed on other pages, like `https://store.steampowered.com/steamaccount/addfunds`, but I believe account related pages cover the majority of cases.

Fix and improve replaceAccountName

---

src/css/augmentedsteam.css
src/js/Content/Features/Community/ProfileHome/CProfileHome.js
src/js/Content/Features/Community/ProfileHome/FCommunityProfileLinks.js
src/js/Content/Features/Community/ProfileHome/FViewSteamId.js

Split out the view steamid feature to its own module, since it has little to do with custom links now.

Split out FViewSteamId from FCommunityProfileLinks, fix imports

---

src/css/augmentedsteam.css
src/js/Content/Features/Community/ProfileHome/FChatDropdownOptions.js

1. Simplify the code a bit: `chatId === friendSteamId`, see https://github.com/SteamDatabase/SteamTracking/blob/5b23cdaef416e2e7f09b4b752970f5f5b38742ef/steamcommunity.com/public/shared/javascript/shared_global.js#L94
2. Hide the menu after clicking on an option (Web chat opens a new window, client chat opens the client)
3. Fix img icon position, move styles to CSS file

Minor improvements to FChatDropdownOptions

---

src/js/Content/modulesContent.js
src/js/modulesCore.js

Since the imports aren't used in these files, `export from` syntax can be used to re-export modules, or am I missing something?

Simplify re-export syntax in aggregated modules

---

src/js/Content/Features/Store/Common/FCustomizer.js

For the apppage customizer, avoid having to query elements twice, just pass the parent element to `customizer.add()`.

Simplify getting parent elements for customizer entries

---

src/css/augmentedsteam-firefox.css

Changed "chrome-extension://" to "moz-extension://" for this.
Was about to create a bug before, but seeing how easy this was to fix, I've created this pull request instead.
As I've already typed the bug report, I guess, why not add it here:
Having a download-icon showing in the screenshot below.
1. Go to any shop-site, e.g. https://store.steampowered.com/app/1097150/Fall_Guys_Ultimate_Knockout/
2. Look for an image in the shop-gallery at the top of the page
3. Open this image
4. The icon is not there in Firefox
This has to do with the image URL for the icon being this:
**chrome-extension://**a1760803-43d5-4425-a810-bcc88155651c/img/screenshot_open.png
Instead of beginning like this in comparison to the fullscreen-icon:
**moz-extension://**a1760803-43d5-4425-a810-bcc88155651c/img/fullscreen …

Fix "screenshot_open.png"-icon not showing in Firefox

---

src/css/augmentedsteam.css
src/js/Content/Features/Store/App/FDLCCheckboxes.js

A number of improvements to DLC checkboxes, supersedes #883:
1. Show options panel by default and copied styles from app_tag (avoids an extra click, unecessary imo).
2. Use modifications to the browser's native checkbox styling instead of a custom background, also added some padding to the label to make them easier to select.
3. Show total price of selected DLCs next to purchase button.
4. (TODO) Maybe replace Steam's "Add all DLC" button instead of adding our own? Though this means the button will be hidden initially just like Steam's if there's a "SEE ALL" button.

Improve FDLCCheckboxes

---

src/js/Core/Html/HtmlParser.js

Simplify the code a bit and strick-check the retrieved value (allow retrieving values like `0`, `false` if needed in the future).
TBD: maybe default to querying `script` tags in `document.body` instead of the whole document?

Improve HTMLParser.getVariableFromDom

---

src/js/Content/Features/Community/ProfileHome/CProfileHome.js

The appid info is located within the deprecated report abuse modal that could be removed at any time. May be worth investigating if there're other ways to get this info.

 Fix missing FInGameStoreLink feature

---

src/js/Content/Features/Store/Wishlist/CWishlist.js

Fixes #977
Tested quite a bit on Chrome, should be just as reliable.
Another option is to observe `#total_num_games`, which will be also updated when the wishlist has finished rendering. If the ajax calls to retrieve wishlistdata from Steam servers all fail, the value will be 0.

Simplify applying wishlist features

---

src/js/Content/Features/Community/Inventory/FInventoryMarketHelper.js

This has been broken for a long time due to a copy error while refactoring from ES, may have been reported before?
~~TBD: This method does a lot of unnecessary work. Seems like all we do is add avg. price of 3 cards to booster packs, the rest is already handled by Steam.~~ Added some comments for now

Fix missing sold volume info in inventory market overview

---

src/js/Content/Features/Store/Common/FCustomizer.js

1. Rename `_updateValue` and `_getValue` to `_updateState` and `_getState` respectively to better reflect their purpose.
2. Be more strict on the type of `targets` accepted.
3. Only need to iterate through elements once.
TBD: This method can probably be simplified further by only accepting a single target. All current customizer options hide/show a single DOM element.

Simplify Customizer.add

---

src/css/augmentedsteam.css
src/js/Content/Features/Community/Inventory/FInventoryGoTo.js
src/js/Content/Modules/SteamFacade.js

Fixes #1030.
1. Simplify inserting "Page number box" html, move styles to CSS file, hide the box when inventory controls are hidden
2. Avoid re-inserting the script on DOM mutations, also fixes `g_ActiveInventory.GoToPage is not a function` errors after filtering by item context (via the dropdown)

Refactor FInventoryGoTo

---

src/js/Content/Features/Community/Inventory/FInventoryMarketHelper.js
src/localization/en.json

1. Our `window.SteamFacade.jq` only works with selections, not utility methods like `$J.get()`
2. Modify the original button, instead of creating duplicate buttons with the same funtionality and having to remove/re-insert HTML for each selected item. Also updated the option label to refect this change.

FInventoryMarketHelper: Fix and simplify one-click-gems option

---

src/html/options.html
src/js/Options/Modules/Data/OptionsSetup.js
src/localization/en.json

Implemented better options grouping in the Store section as proposed in https://github.com/tfedor/AugmentedSteam/pull/875#issuecomment-749636855, and moved some site-wide options to the General section for better discoverability. Also fixed #1031 and some misc. stuff.

Improve options grouping

---

src/css/augmentedsteam.css
src/js/Content/Features/Community/Inventory/FInventoryMarketHelper.js
src/js/Content/Modules/SteamFacade.js

1. Check market price data before writing to data attributes: the data can be `null` if there're no buy orders or sell orders for that item.
2. Use `${item}` instead of `${assetId}` in the link's id attribute to avoid duplicate id values on the page (if the same item is selected more than twice).
3. Avoid hard-coded `publisherFee` value.
4. Hide the scrap actions container as well after item is sold.
5. Add `important` to our styles to avoid being overwritten by inline styles, also prevent the link width from extending beyond its contents.
6. Improve price display in link label: our `Price` contructor formats prices for the storefront, where decimal values are truncated for currencies that don't use decimals, but it's always possible to use decimal values in the market (due to …

FInventoryMarketHelper: Simplify addQuickSellOptions

---

src/js/Content/Features/Community/Inventory/FInventoryMarketHelper.js

Regressed by #1034.
I got this mixed up with the quicksell/instantsell stuff. The difference is that quicksell/instantsell HTML is cleared by Steam on item selection, so we can just re-insert HTML and re-attach our listeners, BUT the gems links are always on the page, so added links need to be removed first to avoid having multiple links/attaching multiple listeners. This reverts it to the way it was done before, only we replace the existing link instead of adding our own.

Fix gems option only working for the first 2 selected items

---

src/js/Content/Features/Community/Inventory/FInventoryMarketHelper.js
src/js/Content/Modules/SteamFacade.js

Improve reliability of some info passed to `_inventoryMarketHelper()`:
1. Remove `market_expired`: the description used to infer this value is localized, and it usually means the item is not marketable either.
2. Replaced `market_marketable_restriction` with a more reliable test for temporary market restrictions, since that value only indicates there will be a restriction, not if the item is currently restricted.
3. Remove `assetType`: this value is only used to test if the selected item is a Steam gift, but it is localized. Replace it with a check for contextId and globalId. Fixes gift prices not showing for non-English locales.

FInventoryMarketHelper: Improve reliability of some info passed to market helper

---

src/js/Content/Features/Community/Friends/FInviteButton.js
src/js/Content/Modules/SteamFacade.js

Related to #584.
At the moment inviting friends to group has to be initiated from the group's homepage, which is slightly inconvenient. This restores the (previous?) behaviour of the invite to group button on friends page, which shows a dialogue that lets you select which group to invite selected friends to.

Improve invite friends to group on friends page

---

src/css/augmentedsteam.css
src/js/Content/Modules/AugmentedSteam.js

Set transition-delay on the visibility property to ensure smooth fade out effect, instead of relying on the transtionstart event and a timeout.

Simplify back-to-top button fade in/out effect

---

src/css/augmentedsteam.css
src/js/Content/Features/Store/App/FPackageInfoButton.js
src/js/Content/Features/Store/Common/UserNotes.js
src/js/Content/Features/Store/RegisterKey/FMultiProductKeys.js
src/js/Content/Features/Store/Wishlist/FExportWishlist.js
src/js/Content/Modules/Prices.js

1. When selecting JSON type, grayout the format area instead of hiding it (which resizes the dialog box).
2. Update button styles for wishlist dialogs and other store features (closes #978) and cleanup html.

Improve wishlist export dialog display, update button styles

---

src/css/augmentedsteam.css
src/js/Content/Features/Store/Common/FCustomizer.js

Proposal to resolve #509.
Move the customizer button to the store controls section above the navigation area, this way we can have a consistent solution for the storefront and app pages. Also changed the popup to show on mouse hover instead of mouse click.
TODO: Use a different color for the button? Right now it's the same as the wishlist link.

Relocate customizer button

---

src/html/options.html
src/js/Content/Modules/UpdateHandler.js
src/js/Core/Storage/SyncedStorage.js
src/js/Options/Modules/Data/OptionsSetup.js

Closes #899.
This option has been no-op since transferring to AS. Looking at the implementation, I can't seem to find cookie entries called LKGBillingCountry or fakeCC anymore (or maybe I don't meet the conditions?). Anyhow, it should be fine to remove this option for now and consider it later if we get a specific feature request.

Remove option "showfakeccwarning"

---

src/css/augmentedsteam.css

Regressed by #1044.
Fix displaying (empty) marketActions section on unmarketable items, and not hiding the section after item had been sold.

Fix marketActions display issue

---

src/js/Background/Modules/SteamStoreApi.js

...so we can always get updated data. This should fix e.g. highlighting after adding/removing wishlist from app pages.

Use "no-cache" for fetching dynamicstore data

---

src/css/augmentedsteam.css
src/js/Content/Features/Store/App/FDLCCheckboxes.js

Actual fixup for #996, replaces the botched attempt at #1006.
Work around invalid `<input>` position by overlapping the `<label>` and `<a>` and giving the label a higher z-index. See the last commit for actual changes.

Fixup FDLCCheckboxes, take 2

---

src/js/Content/Features/Store/Common/FCustomizer.js

Watch the value of `GHomepage.bInitialRenderComplete` instead, should be more reliable.

Avoid using a timeout in customizeFrontPage()

---

src/js/Content/Features/Common/FMediaExpander.js
src/js/Content/Features/Community/Inventory/FInventoryMarketHelper.js
src/js/Content/Features/Community/Market/FPopularRefreshToggle.js
src/js/Content/Features/Community/ProfileEdit/FBackgroundSelection.js
src/js/Content/Features/Community/ProfileEdit/FStyleSelection.js
src/js/Content/Features/Community/ProfileHome/FInGameStoreLink.js
src/js/Content/Features/Community/ProfileHome/FSupporterBadges.js
src/js/Content/Features/Store/App/FNewQueue.js
src/js/Content/Features/Store/App/FOpenCritic.js
src/js/Content/Modules/SteamFacade.js

Update the wrapper for Steam's `v_tooltip()` method, and remove unnecessary calls to `SetupTooltips()` and `BindTooltips()`.
Steam's `SetupTooltips()` call automatically binds tooltips to future added nodes:
https://github.com/SteamDatabase/SteamTracking/blob/603ef3a3f302f2dddcbc76da98c0b170129e1541/steamcommunity.com/public/shared/javascript/shared_global.js#L4533, as long as the tooltip element is a descendant of the added node (this is due to jQuery's [selector context](https://api.jquery.com/jquery/#selector-context) being implemented with the `find()` method internally).

Simplify setting up tooltips

---

src/html/options.html
src/js/Content/Modules/AugmentedSteam.js
src/js/Content/Modules/UpdateHandler.js
src/js/Core/Storage/SyncedStorage.js
src/js/Options/Modules/Data/OptionsSetup.js

After the changes in #832, all this option does now is remove the "About" link under the "Store" dropdown in the header, not really worth an option IMO.

Remove option "hideaboutlinks"

---

src/html/options.html
src/js/Options/Modules/Data/OptionsSetup.js
src/localization/en.json

This feature has a SyncedStorage check, but somehow never had a corresponding option? Since this feature requires fetching storepagedata, maybe it's better to have an option after all.

Add option for showing "excluded from family sharing" notice

---

src/html/options.html
src/js/Content/Features/Common/FHighlightsTags.js
src/js/Content/Modules/UpdateHandler.js
src/js/Core/Storage/SyncedStorage.js
src/js/Options/Modules/Data/OptionsSetup.js

Closes #258.
Hide owned/ignored items is implemented natively on search pages now, and the "Ignore" function on app pages will blur out items on tag pages. These options overlap existing features and can be removed.

Remove options to hide owned/ignored items from search/tag pages

---

src/js/Content/Features/Store/App/FOpenCritic.js

Nothing broken, just to match recent Steam changes to the DOM structure of the right column.

Remove empty leading div in OpenCritic block

---

src/js/Content/Features/Store/App/CApp.js

Steam decided to use duplicate ids for the points shop items block
so this check now fails on apps that have point shop items, but no achievements, e.g. https://store.steampowered.com/app/322330/Dont_Starve_Together/

Fix `hasAchievements` check on app page

---

src/css/augmentedsteam.css
src/html/options.html
src/js/Content/Features/Community/ProfileHome/CProfileHome.js
src/js/Content/Features/Community/ProfileHome/FCustomBackground.js
src/js/Content/Features/Community/ProfileHome/FPinnedBackground.js
src/js/Core/Storage/SyncedStorage.js
src/js/Options/Modules/Data/OptionsSetup.js
src/localization/en.json

Closes #1163.
For static backgrounds, using `background-attachment: fixed` seems to have a negative impact on scrolling performance (googled a bit and I think it's related to the browser having to repaint the image constantly), so add its own element instead.
~~TODO add option~~
~~TODO needs to work with custom backgrounds and background preview~~

Add option to pin the profile background position

---

src/js/Content/Features/Community/SharedFiles/FSubscribeAllDependencies.js

When a user visits a collection page without any subscribable items, the FSubscribeAllDependencies feature crashes due to a null pointer. This is a simple fix for that, to keep the console clear of errors. 
Tested on firefox.

Fix null error on collection pages without subscribable items

---

src/css/augmentedsteam.css

This doubles the height of the item selection box in the collection modification screen. The collection modification screen, normally found at `https://steamcommunity.com/sharedfiles/managecollection/?id=XXXXXXXXXX`, defaults to a height of `200px` on all screen sizes. This PR doubles that to `400px` to improve user experience. 
I tested this on firefox, at various resolutions. I also did a cursory browse of other collection-related pages to ensure that the `.collectionChoiceSection`is only found on this page.

Double height of collection choice section

---

src/js/Content/Features/Common/FHighlightsTags.js

Now that this method no longer handles hiding items, return early if highlighting and tagging is completely disabled.

FHighlightsTags: refactor options object, simplify the code a bit

---

src/js/Background/Modules/ContextMenu.js

If there're no valid keys within selection, open a new tab anyway and display a "no keys found" error message. Closes #1228.

Improve "activate keys in selection" context menu action

---

src/js/Content/Features/Community/ProfileHome/FCommunityProfileLinks.js
src/js/Content/Modules/UpdateHandler.js
src/js/Options/Modules/CustomLinks.js

Up until now an "[ID]" gets automatically added to custom links if missing from the URL, but with the addition of custom links on app pages, this requirement seems unnecessary because not all sites query Steam appids. As for custom links on profile pages, if the user wants the same link on every profile, so be it.
On a side note, it's possible to save links without an "[ID]" to storage because it is only checked when the links are rendered on the options page, not when they're saved (the behaviour is the same since it is checked again in the feature), so to be safe I think we need to make sure existing links all have an "[ID]".

FCommunityProfileLinks: simplify code, stop auto appending "[ID]" to custom links

---

src/html/options.html
src/js/Content/Features/Community/ProfileActivity/CProfileActivity.js
src/js/Content/Features/Community/ProfileActivity/FReplaceCommunityHubLinks.js
src/js/Core/GameId.js
src/js/Core/Storage/SyncedStorage.js
src/js/Options/Modules/Data/OptionsSetup.js
src/localization/en.json

This can technically be rolled into `FHighlightFriendsActivity`, since these links also get checked for highlighting, but I guess it's better to make it a separate feature?
Also replaces and adds highlighting to "followed" links (Steam treats following as joining the app's legacy official group page), though it won't work if the app has a custom group name.
Closes #898.

Add feature to replace community hub links with store page links on friend activity feed

---

src/js/Content/Features/Store/App/FSupportInfo.js

Support info is disabled on DLCs, I assume this is to avoid storing duplicate data? But now it is duplicated for Soundtracks as well, so fix this by attempting to fetch the info for the parent app of DLCs and Soundtracks.

Show the parent app's support info for DLCs and Soundtracks

---

src/js/Content/Features/Store/Common/UserNotes.js

Seems like `_BindOnEnterKeyPressForDialog` skips `textarea` elements, so add back the event listener. "Escape" is handled by Steam already.
Closes #1288.

Restore the ability to press Enter to save a note while typing

---

src/js/setup.js

I guess this isn't needed now minimum FF version has been bumped to 84?

Remove shim for Promise.finally()

---

src/js/Content/Features/Community/FFixAppImageNotFound.js
src/js/Content/Features/Community/Games/CGames.js
src/js/Content/Features/Community/ProfileHome/CProfileHome.js

Closes #1294.
This feature was also applied on wishlists in ES, but I don't think it's needed now.

Reimplement fix_app_image_not_found from Enhanced Steam

---

src/js/Content/Features/Store/Wishlist/FKeepEditableRanking.js

Fixes https://github.com/IsThereAnyDeal/AugmentedSteam/issues/1293#issuecomment-961454031
I don't fully understand why this was broken in the first place, but AFAICT this fixes it.

Ensure Steam's handlers are able to select the original order_input

---

.eslintrc.json
src/js/Content/Features/Community/ProfileHome/FInGameStoreLink.js

Related to #1007.
If the deprecated "report abuse" form isn't available, try to get the appid from the profile's miniprofile hover content. Now this feature also works when not logged in, and should be more future-proof. The additional request shouldn't be a problem, since the exact same page is also fetched if you simply mouseover the avatar.

Improve the logic for finding in-game appid on profile home page

---

src/js/Content/Features/Common/FHighlightsTags.js

Fixes #1310.
Maybe it's worth wrapping highlightNode and addTag functions in try/catch to avoid an error in one causing the other to stop working?

Fix search row tagging

---

src/js/Content/Features/Community/Inventory/CInventory.js
src/js/Content/Features/Community/Inventory/FOneClickGemsOption.js
src/js/Content/Features/Community/Inventory/FQuickSellOptions.js

Found by testing this item from Discord: https://discord.com/channels/301903094080339968/350436837161959424/914137471367913482

Fix quick sell and market overview not appearing for some non-Steam items

---

src/js/Content/Features/Page.js
src/js/Content/Modules/Widgets/SortBox.js

I think `Sortbox.init` only needs to be called on pages that make use of a sortbox? Also fixed dropdown flashing when clicking on the trigger element while the dropdown is open.

Only initiate Sortbox when needed

---

src/css/augmentedsteam-chrome.css
src/css/augmentedsteam-edge.css
src/css/augmentedsteam-firefox.css
src/js/Content/Features/Store/Common/FExtraLinks.js

Avoid clash with a filter rule in one of the stock lists commonly included in ad blockers.
Reported on Discord:
https://discord.com/channels/301903094080339968/568744564261781504/916128124658384906

Add prefix to class name of youtube links

---

src/js/Content/Features/Community/Inventory/PInventory.js

Mainly to avoid loading inventory.js when on https://steamcommunity.com/my/inventoryhistory/.
I couldn't make this work with a match pattern in the manifest, so I copied how it was done for profile_home.js.

Fix inventory page match pattern

---

src/css/augmentedsteam.css

https://store.steampowered.com/recommender/
Since a while ago Steam clipped the bottom section of the interactive recommender page for whatever reason:
This fixes it so the remaining items show up:

Fix clipped bottom section on the interactive recommender page

---

src/js/Background/Modules/SteamStoreApi.js

Minor -- but I think the "about" page is smaller than the revamped news hub in terms of document size.

Get store sessionId from "about" page

---

src/js/Content/Features/Store/App/CApp.js
src/js/Content/Features/Store/App/FSaveReviewFilters.js
src/js/Content/Modules/SteamFacade.js
src/js/Core/Storage/LocalStorage.js

Closes #1313.
Saves preferences for context, language, and min/max playtime filters. For the others:
Purchase type is stored in cookies: https://github.com/SteamDatabase/SteamTracking/blob/9c64b223ab168c4ce4dacf14fccc3e527f5975ef/store.steampowered.com/public/javascript/game.js#L1587; off-topic reviews can be configured in account preferences; as for review type and date range, I think these are usually changed on a per-app basis.

Add feature to save review filter preferences

---

src/js/Content/Features/Store/Common/FDRMWarnings.js
src/js/Content/Features/Store/Common/FITADPrices.js

1. Fix false positives caused by using developer/publisher names (app metadata) to match potential DRM. See https://github.com/IsThereAnyDeal/AugmentedSteam/pull/1339#discussion_r775181124.
2. Fix errors on sub pages.
3. Remove always-falsy condition in false positive detection logic. Surprising no eslint rule caught this ambiguity...
IMO this logic needs to be reworked: we'll need to prevent the notice showing on bundle and sub pages too, not just app pages. But at the moment Resident Evil 5 shouldn't have issues anymore, since we no longer match text in game descriptions, and Special K is unlisted, so this can probably wait until there're an actual case to solve.

Fix DRM warning issues

---

src/js/Content/Features/Store/App/FSaveReviewFilters.js

Playtime filters may not be available on apps with too few reviews, so avoid saving undefined values. The playtime filter shows up erroneously in this case, but that's Steam's problem. Fixup #1337.
Store page to test with: https://store.steampowered.com/app/1838320/OPUS_Vol1/

Fix errors on apps with no reviews or too few reviews to show playtime filters

---

src/js/Content/Features/Community/GroupHome/CGroupHome.js
src/js/Content/Features/Community/GroupHome/FGroupLinks.js
src/js/Content/Features/Community/GroupHome/PGroupHome.js
src/js/Content/Features/Community/ProfileHome/CProfileHome.js

A subpage is any of the announcements/discussions/members... tabs. Should be fine to load group_home.js on all community urls that start with /groups/.

Fix groups home features not loading when reloading a subpage, minor refactoring

---

src/html/options.html
src/js/Options/options.js

1. Cleanup some redundant classes and reformat a bit.
2. Fixed a possible error if a sub option is the last child; factor out common code.

Cleanup options page html

---

src/css/augmentedsteam.css
src/html/options.html
src/js/Content/Features/Community/ProfileActivity/CProfileActivity.js
src/js/Content/Features/Community/ProfileActivity/FToggleComments.js
src/js/Content/Modules/Widgets/ConfirmDialog.js
src/js/Core/Storage/SyncedStorage.js
src/js/Options/Modules/Data/OptionsSetup.js
src/localization/en.json

Closes #1280.
Also...
1. Added a new section "Friend Activity Feed" to the options page to house related options.
2. Added a reusable dialog that displays a "feature hint" notice when the user interacts with a feature for the first time.
This is to avoid duplicate translation efforts, since otherwise every time we add a new feature, we'll need an additional translation string similar to the option for the dialog description. Need suggestions for the style and wording.

Add toggle button to show/hide comments under group announcements on friend activity feed

---

src/js/Content/Features/Store/App/FHowLongToBeat.js

Fixes a typo on "More Information" and "Submit Your Time" links' texts, where a `">` is shown in the end.

Fix How Long to Beat links' texts

---

src/js/Content/Features/Store/App/FSupportInfo.js

Some devs forget to include the protocol in the link, e.g. https://store.steampowered.com/app/1290000/PowerWash_Simulator/, causing the link to break when inserted directly into a `href`.

Fix website links without a protocol

---

src/css/augmentedsteam.css
src/js/Content/Modules/Community/CommentHandler.js
src/localization/en.json

Can happen after an emoticon is listed on the market for example. Since this doesn't happen often, I think dimming the icon and adding a tooltip explaining should be enough?

Fix error if favorited emoticon is no longer accessible

---

src/js/Content/Features/Store/App/FPackageInfoButton.js

I think the original intention behind checking for `.btn_packageinfo` is to exclude bundles, and since bundles are sorted to the bottom, `return` here won't cause problems. Still, it might be better to exclude items by the selector instead.

FPackageInfoButton: clarify and simplify checks

---

src/js/Content/Features/Store/Common/FDRMWarnings.js
src/js/Options/Modules/Data/StoreList.js

( Core issue was instead fixed in #1344 )
~~https://store.steampowered.com/app/1461100/International_Basketball_Manager_22/ is incorrectly identified as an Ubisoft game due to the UPLAY name. I sought to fix this,~~ made minor other improvements on the way.
Additional talking points re FDRMWarnings.js:
- should TAGES DRM be called Tages or TAGES or even Tagès? Steam Store pages are inconsistent in that regard.
- some Ubisoft games require their launcher but don't admit to it, like https://store.steampowered.com/app/647590/Space_Junkies/ and https://store.steampowered.com/app/641080/Trials_Rising/ ; this could be hard-coded akin to the override for excluding certain apps:
```
return !this.context.type === ContextType.APP || (
this.context.appid !== 21690 // Resident Evil 5, at Capcom's …
```

Rename Uplay to Ubisoft Connect / Ubisoft Store as needed & minor DRM capitalisation changes

---

src/js/Content/Modules/UpdateHandler.js

Allow to open the "Changelog" in a new tab when the "Update dialog" appears on a Steam page.

Open changelog in new tab

---

src/html/options.html
src/js/Content/Features/Community/CCommunityBase.js
src/js/Content/Features/Community/FConfirmDeleteComment.js
src/js/Core/Storage/SyncedStorage.js
src/js/Options/Modules/Data/OptionsSetup.js
src/localization/en.json

Closes #1166.
Following the comments in the issue, this feature is enabled by default with a handy checkbox to disable if desired. Works on comments under profiles, UGCs, etc. and is no-op for forum topics which have the native prompt. Though it  doesn't work if the item is opened in an iframe.

Add feature to show confirmation when deleting comments

---

src/css/augmentedsteam.css
src/js/Content/Features/Community/Games/FGamesStats.js
src/js/Content/Features/Store/Wishlist/FWishlistStats.js
src/localization/en.json

Change the Wishlist stats area to display in a hover element. This avoids the area taking up space in the wishlist container, changing its `offsetHeight` value and affecting how row dragging and scrolling behaves. Fixes #1037.
It's tempting to make this feature enabled by default and remove the option, but since it does takes up space and apparently there's an option for showing the "empty wishlist" button as well, I left it as-is for now.

Rework Wishlist stats display

---

src/js/Content/Features/Store/Wishlist/FEmptyWishlist.js
src/js/Content/Features/Store/Wishlist/FOneClickRemoveFromWishlist.js
src/js/Content/Modules/SteamFacade.js

A few months back Steam changed the removal endpoint used on wishlists to match the one used on app pages. We should follow suit.

Update wishlist remove endpoint

---

src/js/Content/Features/Community/MarketHome/FMarketStats.js

The error message is localized so we cannot use its contents to check whether a page failed to load. I think we can just check the message element itself?
Also added some TODOs for consideration when this feature gets a refactor.

Fix check when loading a market history page failed

---

src/js/Content/Features/Store/Common/FRegionalPricing.js
src/js/Content/Modules/CurrencyManager.js
src/js/Content/Modules/Price.js

I also tried to deduplicate error messages in regional pricing because right now they'll be duplicated for each subid. (I thought `console.group()` can group messages under the same label, apparently not. A new group is created for each iteration.)
There's also a possible uncaught error here as well:
https://github.com/IsThereAnyDeal/AugmentedSteam/blob/bb546b37b24a23dfb0c585ee205c888fec3edf03/src/js/Content/Modules/Prices.js#L104
Maybe we should handle it and display prices in the default USD?

Avoid TypeError if we failed to fetch currency conversion rates

---

src/css/augmentedsteam.css
src/js/Content/Features/Community/App/FCommunityAppPageWishlist.js
src/js/Content/Features/Community/FFixAppImageNotFound.js
src/js/Content/Features/Community/GroupHome/FFriendsInviteButton.js
src/js/Content/Features/Community/Inventory/FQuickSellOptions.js
src/js/Content/Features/Community/Inventory/FShowMarketOverview.js
src/js/Content/Features/Community/MarketHome/FMarketStats.js
src/js/Content/Features/Community/ProfileEdit/FBackgroundSelection.js
src/js/Content/Features/Community/ProfileHome/FChatDropdownOptions.js
src/js/Content/Features/Community/ProfileHome/FCustomBackground.js
src/js/Content/Features/Community/ProfileHome/FCustomStyle.js
src/js/Content/Features/Community/ProfileHome/FProfileDropdownOptions.js
src/js/Content/Features/Community/ProfileHome/FTwitchShowcase.js
src/js/Content/Features/Community/ProfileHome/FViewSteamId.js
src/js/Content/Features/Community/SharedFiles/FSubscribeAllDependencies.js
src/js/Content/Features/Store/App/FBadgeProgress.js
src/js/Content/Features/Store/App/FOpenCritic.js
src/js/Content/Features/Store/App/FRemoveFromWishlist.js
src/js/Content/Features/Store/App/FShowCoupon.js
src/js/Content/Features/Store/App/FSteamPeek.js
src/js/Content/Features/Store/App/FWaitlistDropdown.js
src/js/Content/Features/Store/Common/FCustomizer.js
src/js/Content/Modules/AugmentedSteam.js
src/js/Content/Modules/Community/CommentHandler.js
src/js/Content/Modules/Stats.js
src/js/Steam/holidayprofile.js

Steam has been using these new hosts for a while now:
`steamcdn-a.akamaihd.net` -> `cdn.akamai.steamstatic.com`
`steamcommunity-a.akamaihd.net` -> `community.akamai.steamstatic.com`
`steamstore-a.akamaihd.net` -> `store.akamai.steamstatic.com`
Did I manage to catch all of them?
We might be better off storing some images (e.g. throbber.gif) locally, I'll do that later if needed...

Update hosts for Steam assets

---

src/js/Content/Features/Community/ProfileHome/FViewSteamId.js
src/js/Content/Modules/SteamId.js

SteamID64 is commonly displayed as a hex string in the CFX.re platforms (FiveM, RedM). Addition of this way of displaying the SteamID will definitely come in handy for many people.

Added display of SteamID64 Hex variant in profile

---

src/js/Content/Features/Community/Stats/FAchievementSort.js

Avoid using the XML doc which is a deprecated API and has its limitations. New method inspired by SteamDB's browser extension: https://github.com/SteamDatabase/BrowserExtension/blob/0f03f7a470e1b002aec718792da6002476fd1dc0/scripts/community/global_achievements.js#L28
Fixes #1193.
Also took a second pass at only sorting unlocked achievements. The previous attempt at #1261 was to hide locked entries while sorting, but that turned out to be a bad idea, even moreso if we're going to add features like #1463.

Improve handling of achievement sort, take 2

---

src/js/Content/Features/Store/Wishlist/CWishlist.js
src/js/Content/Features/Store/Wishlist/FEmptyWishlist.js
src/js/Content/Features/Store/Wishlist/FKeepEditableRanking.js
src/js/Content/Features/Store/Wishlist/FWishlistHighlights.js
src/js/Content/Features/Store/Wishlist/FWishlistITADPrices.js

Avoid using the display of the nothing-to-see-here message because it might be affected by race conditions, and the message doesn't necessarily mean the wishlist is empty, it could be that there're no results after applying filters.

Use the wishlist data array to determine whether to apply features

---

config/manifests/base.json
src/js/Content/Features/Community/Inventory/PInventory.js

Changes:
1. removed `support.steampowered.com/*` since it redirects to `help.steampowered.com/*`
2. removed `translation.steampowered.com/*` since it's retired
3. removed `store.steampowered.com/dynamicstore/*` since it just shows an error page
4. added `store.steampowered.com/supportmessages`: links to account warning messages, no header and not suitable to augment
5. added `store.steampowered.com/video/*`: Steam's video streaming service
6. added `login.steampowered.com/*`: new login domain that may get used
7. added `steamcommunity.com/comment[/*]`:  blank page, only valid link is probably `https://steamcommunity.com/comment/Recommendation/formattinghelp`
8. Avoid using a wildcard to match end of the pathname, e.g. `*.steampowered.com/steamaccount/addfunds*`, since there might be …

Fix and improve match patterns for content scripts

---

src/css/augmentedsteam.css
src/js/Content/Features/Community/FriendsAndGroups/FFriendsSort.js
src/js/Content/Features/Community/FriendsAndGroups/FGroupsSort.js
src/js/Content/Features/Community/MarketHome/FMarketSort.js
src/js/Content/Modules/DOMHelper.js
src/js/Content/Modules/Widgets/SortBox.js
src/js/Core/Storage/SyncedStorage.js

Refactor to use our `Sortbox` implementation to resolve #1369, while fixing a couple of bugs this feature had, the most broken one being sorting then changing page controls, because we were inserting rows into the wrong container. Also fixed sorting by price (we were using string comparison so e.g. `"10" < "2"`). Based on the implementation from groups and friends sort, and cleaned up those feature a bit while at it.
A problem I encountered was we have to reset the sortbox in certain conditions, and I haven't found a good way to do that other than removing and re-inserting the element.
Another thing to note is we don't add sorting options for listings on hold, unlike adding lowest prices. I suppose they work the same so we can probably just query the container and add it and hope for the …

Refactor market listings sort

---

src/js/Content/Features/Community/Games/FGamelistAchievements.js
src/js/Content/Modules/Stats.js

Fixes the text display for locales which display total count before unlocked count, and which place the % sign differently.
For posterity: we could use the new method like #1470 to get the `g_rgAchievements` object, which will be much cleaner, but we use the appid to query stats pages, and sadly some games will redirect to a url with the app name, causing query parameters to be erased. For these games we'll need to do 2 fetches, which will slow down the whole process.

Deduplicate and improve `Stats.getAchievementBar`

---

src/js/Content/Modules/User.js
src/js/Core/Html/HtmlParser.js

Return string variables directly instead of going through `JSON.parse`. It should work the same, and allows matching single-quoted strings too.

Simplify matching string variables in scripts

---

src/css/augmentedsteam.css
src/js/Content/Features/Store/App/CApp.js
src/js/Content/Features/Store/App/FForceMP4.js
src/js/Content/Features/Store/App/FFullscreenScreenshotView.js
src/js/Content/Features/Store/App/FHDPlayer.js
src/js/Core/Utils/TimeUtils.js

Simplifed a bunch of stuff, fixed the case when switching from HD back to SD reloads the video (there is no `data-sd-src` attribute on videos, so we were setting the `src` to `undefined` and triggering the `onerror` handler), and removed 2 surprising behaviors I don't think makes sense
1. Override Valve's auto switch to HD when putting a video in fullscreen
2. When the slider is expanded first time after the page was loaded set videos definition to HD
Also added the feature to auto hide overlay and cursor while the video is playing. Mainly useful in fullscreen, but it works in normal view as well.
Issues remaining:
1. If autoplay and HD are enabled, the video will be paused, with an error `DOMException: play() failed because the user didn't interact with the document first`. A possible …

Refactor FHDPlayer, add feature to auto hide overlay and cursor while playing

---

src/js/Content/Features/Common/FHighlightsTags.js
src/js/Content/Features/Store/Storefront/CStoreFront.js

Changing the 2 new options re-renders this section.
Also added checks to avoid errors when accessing `classList` in highlights.

Observe mutations in the top sellers tab of the storefront

---

config/manifests/chrome.json

Without this, source map urls get blocked with `System error: net::ERR_BLOCKED_BY_CLIENT` on Chrome in production mode. Works fine on Firefox so only add to the manifest for Chrome.

Allow Chrome devtools to access source maps

---

src/css/augmentedsteam.css
src/js/Content/Features/Community/Inventory/CInventory.js
src/js/Content/Features/Community/Inventory/FQuickSellOptions.js
src/localization/en.json

Display error message if listing an item failed (or endpoint threw) or requires Steam Guard confirmation (there're different messages for mobile and email auth, but we'll just show a generic message since I believe users are capable of figuring it out themselves).
Refactor getting market prices (related to #1513):
1. Add "country" parameter to the market/itemordershistogram endpoint. Seems to help with avoiding 429s.
2. Cache market prices to reduce requests for duplicate items.
3. Better error logging and added TODOs

Improve quick sell error handling

---

src/js/Content/Features/Community/FriendsAndGroups/FGroupsManageButton.js
src/js/Content/Features/Community/FriendsAndGroups/FGroupsSort.js
src/js/Content/Features/Community/FriendsAndGroups/FInviteFriendsToGroup.js

Feels weird that the links are still clickable afterwards, so just remove the entire row.
On a side note, we shouldn't be setting the display either, because otherwise the row will show up again when filtering by keywords. Steam's native "leave group" action has this bug. Dunno if it's worth fixing, but at least make it work better for our feature.

Remove group row after leaving instead of setting opacity

---

src/css/augmentedsteam.css
src/js/Content/Features/Common/FEarlyAccess.js
src/js/Content/Features/Community/CCommunityBase.js
src/js/Content/Features/Community/Games/CGames.js
src/js/Content/Features/Community/ProfileActivity/CProfileActivity.js
src/js/Content/Features/Community/Recommended/CRecommended.js

Run the feature on all community pages instead, since splitting it out to relevant contexts risks missing out on pages where we don't have specific features, e.g. global achievements page and individual reviews.

Improve community EA banners and tweak image sizes

---

config/manifests/base.json
config/webpack/webpack.common.cjs
src/js/Content/Features/Store/Cart/CCart.js
src/js/Content/Features/Store/Cart/FCartHistoryLink.js
src/js/Content/Features/Store/Cart/PCart.js
src/js/Content/Modules/Context/ContextType.js

Users have noted this feature is difficult to find in the account preferences page, so add it to the cart page itself. There's still the issue where if Steam empties your cart after some time of inactivity, the cart button will be hidden. But I'm not sure if it's desirable to always show the cart button (though most e-commerce sites I use are like that).
In preparation for adding features to the cart/history page: https://github.com/IsThereAnyDeal/AugmentedSteam/issues/1143#issuecomment-873598311.

Add Cart page context and feature to show cart history link

---

src/js/Background/Modules/SteamStoreApi.js
src/js/Content/Features/Common/FEarlyAccess.js
src/js/Content/Features/Community/Badges/CBadges.js
src/js/Content/Features/Community/Badges/FBadgeCalculations.js
src/js/Content/Features/Community/FriendsAndGroups/FFriendsSort.js
src/js/Content/Features/Community/MarketHome/FMarketStats.js
src/js/Content/Features/Community/ProfileActivity/FToggleComments.js
src/js/Content/Features/Community/ProfileHome/FInGameStoreLink.js
src/js/Content/Features/Community/Recommended/FReviewSort.js
src/js/Content/Features/Community/SharedFiles/FSubscribeAllDependencies.js
src/js/Content/Features/Store/App/FBadgeProgress.js
src/js/Content/Features/Store/Common/FExtraLinks.js
src/js/Content/Features/Store/Wishlist/FWishlistUserNotes.js
src/js/Content/Modules/AugmentedSteam.js
src/js/Content/Modules/Stats.js
src/js/Content/Modules/User.js
src/js/Content/Modules/Widgets/SortBox.js
src/js/Core/Html/Html.js
src/js/Core/Html/HtmlParser.js
src/js/Core/Utils/StringUtils.js
src/js/Options/Modules/CustomLinks.js
src/js/Options/Modules/Sidebar.js

Mainly removed some methods on `HTMLParser` that were just aliases of methods on `HTML`, and renamed them for clarity. (I could never rememeber the capitalization `HTMLParser.htmlToDOM` vs `HTMLParser.getVariableFromDom`, so I chose the latter and deprecated the former.)

Remove `HTML` methods from `HTMLParser`

---

src/js/Content/Features/Community/Stats/FShowHiddenAchievements.js

Fixes https://github.com/IsThereAnyDeal/AugmentedSteam/commit/e72b62fc0096ecbc75e6dea055d0765280d7f8bb#commitcomment-88901300, in case it gets forgotton...
IMO it's easier to leave the row intact for now.

Disable button after showing hidden achievements

---

src/js/Content/Modules/User.js

An alternative is to find the `g_rgWalletInfo` object, which has a `wallet_country` key. Not sure if it's always present and equal to store country though.

Improve store country detection on market-related pages

---

src/js/Content/Modules/AugmentedSteam.js

This is leftover from ES where the script passed to `runInPageContext()` was formed by string concatenation.

Avoid trimming game name in launch random app modal title

---

src/html/options.html
src/js/Content/Modules/AugmentedSteam.js
src/js/Options/Modules/OptionsTranslator.js
src/js/config.js
src/localization/en.json

Replaced the `OptionsTranslator._localizeHtml` method now that HTML tags are not allowed in localization strings.
Also added our Discord to the config file. We may want an entry for the ITAD site as well (https://isthereanydeal.com/) to support using the new site once it's ready?

Make about/footer section on Options translatable

---

src/localization/en.json

We don't have CSS to handle these and it doesn't seem necessary.

Remove newline char in localization string

---

src/js/Content/Features/Store/Common/FAlternativeLinuxIcon.js

Improves icon visibility when the tab is highlighed and focused at the same time.
Before:

Completely darken alternative linux icon on tab focus

---

src/js/Content/Features/Community/Workshop/FBrowseWorkshops.js
src/js/Core/Html/Html.js

Also fixed a possible error if the `workshop_state` value is an empty string (initial value).
Note: I couldn't figure out why removing the `onclick` attribute doesn't remove the click listener, so I ran it through the sanitizer. Also changed the `HTML.replace` method to return the first element of the replaced nodes, since it doesn't make sense to return the original node.

Fix tab image placement after clicking tabs on workshop home 

---

config/manifests/base.json

I don't know the history behind this, but apparently `https://steamcommunity.com/workshop` is an alias for `https://steamcommunity.com/sharedfiles`. And for UGCs, these links are the same:
`https://steamcommunity.com/sharedfiles/filedetails/?id=2897893116`
`https://steamcommunity.com/workshop/filedetails/?id=2897893116`
`https://steamcommunity.com/sharedfiles/filedetails/2897893116`
`https://steamcommunity.com/workshop/filedetails/2897893116`
The first one is the most common one generated by Steam, the second can sometimes be seen, and the last 2 I found by accident. These all seem reasonable so I modified the match patterns to support them.

Add more match patterns for sharedfiles related pages

---

src/js/Content/Features/Store/App/CApp.js
src/js/Content/Features/Store/App/FRemoveDupeScreenshots.js

Removes duplicate screenshots (specifically those with duplicate `id`s) otherwise the highlight player will keep scrolling back to the first one. Someone mentioned this on Discord before but back then I didn't know how to code 😄.
Store page for testing: `https://store.steampowered.com/app/1201270/__A_Space_for_the_Unbound/`
(They might fix it at some point)

Add feature to remove duplicate screenshots on store pages

---

src/js/config.js

The old host has been redirecting for a while now.

Update config `ApiServerHost`

---

src/css/augmentedsteam.css
src/js/Content/Features/Community/Inventory/FQuickSellOptions.js

This changes the color of quick sell buttons to grey so the white text is easier to read. Also avoids CSS tricks to override the display property. Another option is to use blue, like SteamDB does.

Change the color of quick sell buttons

---

src/js/Content/Features/Community/MarketHome/FMarketLowestPrice.js
src/localization/en.json

I no longer think it makes sense to retry after 429s. From my experience, it lasts for at least 1 hour and resets every time you access the endpoint. 30 seconds is too long anyway and users will simply think the page has stalled, so change it to alert the user immediately and avoid sending more requests.
Also increased the delay between requests to 2 seconds as discussed in https://github.com/IsThereAnyDeal/AugmentedSteam/issues/1594#issuecomment-1453807286.
Closes #1594.

FMarketLowestPrice: Alert the user and avoid sending requests once timed-out, increase delay

---

src/js/Background/Modules/SteamCommunityApi.js
src/js/Content/Features/Community/Recommended/FReviewSort.js
src/localization/en.json

Fixes #1526.
TODO
1. `SteamCommunityApi.updateReviewNode` only updates the node, but we need to update helpful, funny, visibility, and (the newly introduced) awards data too. The page reloads after giving an award though...
2. Reviews are cached for an hour, but may contain outdated data, especially after Steam introduced content checking. Maybe there should be a "force update" feature?
3. There're no doubt more cases to handle, e.g. developer or support accounts that have the ability to reply to or flag reviews. No idea what to do until somebody raises an issue.

Refactor and fixup reviews sort

---

src/js/Content/Features/Store/Wishlist/CWishlist.js
src/js/Content/Features/Store/Wishlist/FKeepEditableRanking.js
src/js/Content/Features/Store/Wishlist/FOneClickRemoveFromWishlist.js
src/js/Content/Features/Store/Wishlist/FWishlistUserNotes.js

1. Steam introduced a bug in their changes: https://github.com/SteamDatabase/SteamTracking/blob/fad88f22ab535c83349243be1f8f83dddbf61557/store.steampowered.com/public/javascript/wishlist.js#L331, should use `+=` because there's a closing tag blow. This causes jQuery to render an additonal text node. For testing:
```js
$J('<div class="purchase_container" >\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t</div>')
```
2. Fixup 29bd5012e905997f7b90f189a5ea7324d8a3b73f. We also need to update the initial container height (which is done through `g_Wishlist.Update()`) because it changes the scroll area, and is used to calculate what elements to load/unload. Without this there'll be weird issues if you scroll to the bottom.
3. Avoid having to manually check which nodes have been processed already for every …

Fix wishlist observer

---

src/js/Background/Modules/SteamStoreApi.js
src/js/Background/background.js
src/js/Content/Modules/Data/DynamicStore.js

1. Removed a bunch of outdated stuff: `await DynamicStore` isn't used anywhere, and `getAppStatus()` calls into indexedDB which checks the expiry.
2. `_fetch()` is only called in `getRandomApp()`, which is already guarded by `User.isSignedIn` in `AugmentedSteam.js`. Maybe we should "force fetch" dynamic store data in this case?

Simplify DynamicStore

---

src/js/Content/Features/Community/ProfileActivity/CProfileActivity.js
src/js/Content/Features/Community/ProfileActivity/FPatchBlotterFunc.js
src/js/Content/Features/Store/App/FPatchHighlightPlayer.js

Steam finally fixed the volume cookies after over 9 years, according to the date of changes tracked by SteamDB, see https://github.com/SteamDatabase/SteamTracking/commit/b7e8996a9a2a26296df60b252a608b3dc1c96ab1#diff-36b4bfb688a77058a217082422191c34df62ffee5e397812472c0405d6b06732. Unfortunately the issue with unmuting still remains.
Also moved blotter patches to own file so it's easier to locate. I believe we'll need to do this to adopt MV3 anyway.

Remove some highlight player function patches

---

src/js/Content/Features/Store/App/FSteamDeckCompatibility.js

Only regular apps (and software) display this info. I meant to add this back then but forgot to 😅.

Only check deck compat data for regular apps

---

src/js/Content/Features/Store/Storefront/CStoreFront.js

There's not much point in monitering this section while it's broken, so just avoid the error for now.

Fix error in the Top Sellers tab

---

src/js/Content/Features/Common/FEarlyAccess.ts

This makes it so the EA banner component is rendered in place if the original image. Feel free to remove the comment if it's just stating the obvious 😅.

Fix EA banner position

---

src/js/Background/Modules/Api.js
src/js/Content/Features/Community/Badges/CBadges.js
src/js/Content/Features/Community/FriendsAndGroups/FGroupsManageButton.js
src/js/Content/Features/Community/Inventory/FEquipProfileItems.js
src/js/Content/Features/Community/Inventory/FQuickSellOptions.js
src/js/Content/Features/Community/MyWorkshop/FWorkshopFileSizes.js
src/js/Content/Features/Community/ProfileStats/CProfileStats.js
src/js/Content/Features/Community/Workshop.js
src/js/Content/Features/Community/Workshop/FBrowseWorkshops.js
src/js/Content/Features/Community/WorkshopBrowse/FWorkshopSubscriberButtons.js
src/js/Content/Features/Store/RegisterKey/FMultiProductKeys.js
src/js/Content/Features/Store/Wishlist/FEmptyWishlist.js
src/js/Content/Modules/RequestData.js

We're not sending files or blobs, so we don't really need to use `FormData`, a URL-encoded string will do. Also removed some URL checks that I think are redundant.

Simplify post request body content type

---

src/js/Content/Features/Store/App/FDLCCheckboxes.js
src/js/Content/Features/Store/Common/AddToCart.js
src/js/Content/Features/Store/Common/FAddToCartNoRedirect.js

As a follow-up, I'm planning to move handling free promotions to it's own method (similar to how Steam handles the Add to Library option), but that'll have to wait until Steam fixes their own stuff.

Fix some issues with add-to-cart-no-redirect

---

src/js/Background/Modules/ITADApi.js
src/js/Content/Modules/User.js

The `steamCountry` cookie is now `HttpOnly`, and the `?cc=` trick has long been inoperative. It still works when logged out, so I guess we can keep the logic, though we should probably check if the value is one of `CountryList`.

Simplify getting store country

---

src/js/Content/Features/Store/Wishlist/FKeepEditableRanking.js

A simple QoL improvement and mimics Steam's behaviour.

FKeepEditableRanking: select all text when focusing input field

---

src/js/Background/Modules/IndexedDB.js
src/js/Background/Modules/SteamCommunityApi.js
src/js/Background/background.js
src/js/Content/Features/Community/Recommended/FReviewSort.js

This just removes the update review action since the whole idea is flawed. Supersedes #1641.
Some things left to consider:
1. Add a "force fetch" button if there's demand.
2. Add progress info the waiting dialog (and a way to abort the whole thing). That goes for all features that might fetch a lot of pages though.

FReviewSort: remove update review background action

---

src/css/augmentedsteam.css
src/js/Content/Features/Store/Search/FSearchFilters.js
src/js/Content/Features/Store/Search/Filters/DiscountPercentSearchFilter.js
src/localization/en.json

This PR adds a new filter to the Steam search page for filtering the results by the discount percentage. I've used the existing Review Count filter as a template for this. 
Both the minimum and maximum desired percentage can be specified (or left blank individually). Any search results that are not discounted at the moment are treated as having 0% discount.
Satisfies issue #938 .

Add discount percentage filter on search page

---

src/js/Content/Features/Common/FKeepSSACheckboxState.js

Save current checkbox state to preference, instead of the invert of current preference. This fixes the case where if you have 2 (or an even number) of tabs open and enable the checkbox on both, the resulting preference will be `false`.

FKeepSSACheckboxState: check current checkbox state when saving preference

---

src/js/Content/Features/Community/Inventory/CInventory.js

When clicking items in the new item row, we're actually clicking the children of the selector, so use `.closest` instead.

Fix clicking items in the new item row not adding features

---

src/js/Content/Features/Store/Common/FExtraLinks.js

This change changes the search query to display more relevant YouTube videos by making the search queue less restrictive.
All search queries were tested in incognito mode to prevent personal recommendations. Tested recommendations for an unreleased game (for which there is no PC video yet) and an already released one.
Possibly related to https://github.com/IsThereAnyDeal/AugmentedSteam/issues/707
---
**Gameplay query (game not yet released on Steam)**
Before:
After:
---
**Review query (game not yet released on Steam)**
Before:
After:
The results are now at least relevant to this game.
---
**Gameplay query (game already released on Steam)**
Before:
After:
The results are identical.
---
**Review query (game already released on Steam)**
Before:
After:
The results are more relevant.

Fix YouTube query for Gameplay and Reviews to make them more relevant

---

src/js/Core/Storage/Storage.ts

Fixes an error in the FF dev console: `Uncaught (in promise) Error: Type error for parameter items (Expected a plain JavaScript object, got a Map) for storage.StorageArea.set.`

Fix export/import settings

---

src/css/augmentedsteam.css

Other elements on the page with solid backgrounds have bottom margins to space them out so they don't touch. This includes product/bundle purchase boxes, SteamDB pricing, Franchise links, etc. This PR adds such a margin to `es_drm_warning` so that it doesn't visually connect to whatever element appears below it.
Fixes #1736

Add 10px bottom margin to drm warning to match other UI

---

config/manifests/base.json
config/webpack/webpack.common.cjs
src/js/Content/Features/Store/Licenses/CLicenses.js
src/js/Content/Features/Store/Licenses/FLincensesSummary.js
src/js/Content/Features/Store/Licenses/PLicenses.js

Do you ever wonder how many games you bought in a certain year as opposed to just claiming them for free?
Or how many games you were gifted in total? All the data is there, you just need to crunch some numbers, now automated!
Applies to [Home > Account > Licenses and product key activations](https://store.steampowered.com/account/licenses/)
Adds a summary table of games added to the account per year per category.
Tested in Chrome.
Fully translated using existing Localization lines.

Add yearly summary table for licenses page

---

src/js/Content/Features/Community/ProfileEdit/CProfileEdit.js

Steam changed the root node for some reason, so this fixes and simplifies detecting whether the page has loaded.

Fix profile edit page features sometimes not loading

---

src/js/Content/Modules/Prices/PriceOverview.svelte

Fix voucher and DRM texts displayed next to “Current best:” on app pages

---

src/js/Content/Modules/Prices/BundleOverview.svelte

The API returns all bundles now, so we need to add a check for live bundles.
Fixes #1837.

Avoid showing bundle header when there're no live bundles

---

src/js/Content/Features/Community/FriendsAndGroups/FGroupsManageButton.js
src/js/Content/Features/Community/Inventory/FQuickSellOptions.js
src/js/Content/Features/Community/Workshop.js
src/js/Content/Features/Store/RegisterKey/FMultiProductKeys.js
src/js/Content/Modules/RequestData.js

Decoupled `RequestData.post` from `RequestData.getHttp`. Almost all endpoints we send POST requests to return JSON data, and we have error handling in case the request failed so it's not really necessary to use the progress bar.

Refactor `Request.post` to return data as json by default

---

src/css/augmentedsteam.css

Class names are mangled now and this issue has been fixed by Steam.

Remove unused CSS for interactive recommender page

---

src/js/Content/Features/Common/FDisableLinkFilter.js

This feature wasn't working at all -- `href.search` was referencing the native String#search function. Also added a check to skip censored links.

Fixup disable link filter handler

---

src/js/Content/Features/Store/App/CApp.js
src/js/Content/Features/Store/Wishlist/CWishlist.js

Fixes a copy error; the dependency on`FExportWishlist` should also be weak since it's just for display order.

Fix some feature dependencies

---

src/js/Content/Features/Store/AgeCheck/CAgecheck.js
src/js/Content/Features/Store/Cart/CCart.js
src/js/Content/Features/Store/Funds/CFunds.js
src/js/Content/Features/Store/RegisterKey/CRegisterKey.js

These store page contexts need to extend `CStoreBase` to enable features like highlights in search results and focus search box by pressing "s". I might have broken these a while ago 😅

Fix missing features on some store pages

---

src/js/Content/Features/Store/App/FBadgeProgress.svelte

It's perfectly normal for a game to not have cards, so avoid throwing an error. Fixup #1876.

Don't throw an error if game doesn't have cards

---

src/js/Background/MessageHandlerInterface.ts
src/js/Background/Modules/AugmentedSteam/AugmentedSteamApi.ts
src/js/Background/Modules/Cache/CacheApi.ts
src/js/Background/Modules/Community/SteamCommunityApi.ts
src/js/Background/Modules/Inventory/InventoryApi.ts
src/js/Background/Modules/IsThereAnyDeal/ITADApi.ts
src/js/Background/Modules/Store/SteamStoreApi.ts
src/js/Background/Modules/UserNotes/UserNotesApi.ts
src/js/Content/Modules/Facades/SteamCommunityApiFacade.ts
src/js/Content/Modules/Facades/SteamStoreApiFacade.ts

These seem redundant because the final value is awaited. Maybe a linter can catch these?

Remove redundant async/await from background handler

---

src/js/Content/Features/Store/App/FSteamPeek.ts
src/scriptlets/Store/App/SteamPeek/bindHover.js
src/scriptlets/Store/App/SteamPeek/decorateItems.js

The reason why it's broken seems to be because dynamic scripts are not guaranteed to run immediately and in the order they were inserted (so the `a:last-of-type` selector always selects the same node).
The way to avoid this potential footgun is to make `DOMHelper.insertScript` return a promise that resolves on load, but for this particular case, I think it's better to just run a single script instead.

Fix steampeek hovers

---

src/js/Content/Modules/UserNotes/UserNotesAdapter.ts
src/js/Core/AssertNever.ts
src/js/Options/Modules/Options/StoreOptions.svelte

In the old options logic, `UserNotesAdapter.getAdapter` was called prior to the new value being saved to storage, but now by the time it's called the new value had already been saved, so we need to set the current adapter when loading options, otherwise it will always return the new adapter...
We should probably have error handling here as well.

Fix switching notes adapter

---

src/js/Content/Features/Community/Inventory/FEquipProfileItems.ts
src/js/Content/Features/Community/ProfileStats/FShowHiddenAchievements.ts
src/js/Content/Modules/SteamApi.ts
src/js/Content/Modules/User.ts

Reworks the `User.accessToken` getter to `User.getWebApiToken()` so it's more descriptive and doesn't collide with ITAD's `AccessToken` class.

Refactor getting web api token

---

src/js/Core/Currencies.ts
src/js/Core/Errors/Errors.ts
src/js/Options/Data/Settings.ts

I think relying on compile-time `readonly` should be enough?

Remove runtime `Object.freeze` calls

---

src/css/augmentedsteam.css

i.e. when the DLC checkboxes feature is not applied.
Example store page `https://store.steampowered.com/app/1113560/NieR_Replicant_ver122474487139/`

Don't add DLC row margin when app has no paid DLCs

---

src/js/Content/Modules/Prices/BundleOverview.svelte

Closes #1970
Hello, I am one of the developers of the [Steam Currency Converter](https://chromewebstore.google.com/detail/steam-currency-converter/ocabaebkfcojookdnihccpcngaaigfan). 
We use AS daily and pay close attention to its newly introduced features. To improve price parsing on bundle tiers, we suggest adding a class name for those prices. This change would significantly ease our efforts in converting these prices.
Best regards.

Put class on bundle-tier to make it parsable later (#1970)

---

src/js/Background/Modules/IsThereAnyDeal/ITADApi.ts

Currently, when the periodic import of Library or Waitlist is enabled, a sync call with ITAD is forced on every page load.  This ends up having a noticeable performance effect on Steam given a larger wishlist and/or collection size.  This PR switches off the `force` boolean such that the sync calls will instead check the expiry timers set after a previous sync call.
Fixes #1976

Avoid forced sync calls on every page load

---

src/css/augmentedsteam.css
src/js/Content/Features/Store/App/CApp.ts
src/js/Content/Features/Store/Common/ExtraLinks/ExtraLink.svelte
src/js/Content/Features/Store/Common/FExtraLinksApp.ts
src/js/Content/Features/Store/Common/FExtraLinksAppError.ts
src/js/Content/Features/Store/Common/FExtraLinksCommon.ts

1. Remove `checkPrerequisites()` calls from extra link features, and just throw if node not found
2. Split out logic for extra links on app error pages
3. Fix app error pages rendering an empty div when all extra links are disabled

Refactor extra links

---

src/js/Content/Features/Community/ProfileStats/FAchievementSort.ts

Test the format before getting date formats if language is English. I'm starting to wonder if there're other unstable locales 😥. Fixes #1908.

FAchievementSort: fix parsing US date formats

---

src/js/Content/Modules/Prices/PriceOverview.svelte

This was meant to be part of #1912. I did test this back then, but I don't know of any game that offers this now 😅
The styles on Steam's side haven't changed since they were added so this should still work
https://github.com/SteamDatabase/SteamTracking/blame/1e625e7d29e850cf9d9e9b3fc33ba42a09d765cc/store.steampowered.com/public/css/v6/game.css#L893

Fix space between prices and the purchase container

---

src/js/Content/Features/Community/GroupHome/CGroupHome.ts
src/js/Content/Features/Community/GroupHome/FFriendsInviteButton.svelte
src/js/Content/Features/Community/GroupHome/FFriendsInviteButton.ts
src/js/Content/Features/Community/GroupHome/FGroupLinks.ts

Group links should work when logged out, so revert to the old logic for getting group id prior to #1352.

CGroupHome: add a more reliable fallback to get group id; svelte-fy features

---

src/js/Background/Db/IndexedDB.ts
src/js/Background/Modules/ContextMenu/ContextMenu.ts
src/js/Background/background.ts
src/js/Content/Features/Community/TradeOffer/PTradeOffer.ts
src/js/Content/Features/Page.ts
src/js/Content/Modules/Currency/CurrencyManager.ts
src/js/Content/Modules/User.ts
src/js/Core/Localization/Localization.ts
src/js/Options/Data/Settings.ts
src/js/Options/OptionsPage.svelte
src/js/bootstrapDomPurify.ts

I think these `.then` argument types are to make TS happy? Otherwise you run into `Type of 'await' operand must either be a valid promise or must not contain a callable 'then' member` when doing `await SomeClass` 🤔
In any case, we shouldn't be calling these `.then` or `.init` methods externally, so mark them as private and simplify `.then` arguments.

Improve init methods

---

src/js/Content/Features/Store/Wishlist/FExportWishlist.ts
src/scriptlets/Store/Wishlist/exportWishlistModal.js

I think a custom solution is better here, similar to the user notes dialog. Also fixes an issue with the old `exportWishlist()` function being executed multiple times and triggering a browser permissions warning.

Use a custom dialog for export wishlist

---

src/js/Content/Features/Community/ProfileStats/FAchievementSort.ts

Fixes #2036. Also made the options field required since we're not going to be using the default English.

Fix not passing locale to DateTime.fromFormat

---

src/js/Content/Features/Community/ProfileHome/FWishlistProfileLink.svelte
src/js/Content/Features/Store/App/FPlayers.svelte

Also attempt to format the value using Steam locale first, otherwise fallback to browser locale. Maybe we should extract the formatter into a util class?

Fix profile wishlist count for non-English locales

---

src/css/augmentedsteam.css
src/js/Content/Features/Store/App/FDLCCheckboxes.ts

For testing: `https://store.steampowered.com/app/493340/`
Had to revert to the old way of inserting the checkbox within the row, fortunately there's the `:has()` selector now, though I added a fallback until we increase the min version.

Fix checkbox position on recommended DLC row

---

src/js/Content/Features/Store/Common/UserNotes/NotesForm.svelte

I didn't look into the details, but it seems like FF doesn't fire the change event when the input loses focus due to a programmatically fired click event. This is just a quick workaround for the issue.
Fixes #2057

NotesForm: Dispatch change event on input when hitting Enter

---

src/js/Core/Html/Html.ts

All uses of `HTML.formatUrl` formats a whole URL, so we should leave special characters as-is.
Fixes #2061.

Avoid escaping reserved characters when formatting URL

---

src/js/Content/Modules/Widgets/AugmentedSteamMenu.svelte
src/js/Core/GameId/AppId.ts
src/scriptlets/Store/Wishlist/hiddenApps.js

Seems like most store assets are now linked from `shared.steamstatic.com`, and only community stuff are left on `cdn.steamstatic.com`

Add support for fastly CDN, make CDN optional

---

src/js/Core/Storage/SyncedStorage.ts

I tried updating @types/webextension-polyfill to reflect this, but there're a couple of breaking changes that make it not so straight forward (mainly type changes from `any` to `unknown`), so I just restored the old logic for now.
Fixes the out of capacity dialog not showing on FF, related to #2065.

Fix for `browser.storage.sync.QUOTA_BYTES_PER_ITEM` being undefined on FF

---

src/js/Background/EAction.ts
src/js/Background/Modules/Store/SteamStoreApi.ts
src/js/Background/Modules/Store/_types.ts
src/js/Content/Features/Community/ProfileHome/FWishlistProfileLink.svelte
src/js/Content/Features/Community/ProfileHome/FWishlistProfileLink.ts
src/js/Content/Modules/Facades/SteamStoreApiFacade.ts

`/IWishlistService/GetWishlistItemCount/` now returns the specified steamid's count, and no longer requires an access token.

Refactor wishlist profile link count

---

src/js/Content/Features/Community/MyWorkshop/FWorkshopFileSizes.ts
src/js/Content/Features/Community/WorkshopBrowse/FWorkshopSubscriberButtons.ts
src/js/Content/Modules/Facades/SteamFacade.ts
src/js/Core/Modals/BlockingWaitDialog.ts
src/js/Core/Modals/BlockingWaitModal.svelte
src/scriptlets/SteamScriptlet.js

Based off #2060.
Dunno if this is worth it, but it does avoid setting innerHTML.

BlockingWaitDialog: Use a svelte component to update status

---

src/js/Content/Modules/Prices/BundleOverview.svelte

- Add getNonEmptyTiers function to remove tiers without games
- Prevent display of "Tier X includes 0 items" sections
- Add JSDoc documentation for maintainability
The change improves UI clarity by filtering out bundle tiers that  contain no games, while maintaining all functionality for populated tiers.
Fixes #2120

fix: filter out empty tiers in bundle overview (#2120)

---

src/css/augmentedsteam.css

Added more height to badge binder view because the text was getting outside on some badges. Tried to rewrite with flex or grid, it's really messy, reverted to fixed height.

Updated badge binder view height

---

src/js/Content/Modules/Widgets/AugmentedSteam/AugmentedSteamWarnings.svelte

Closes #2104
`LoginWarning` was not checking for the presence of the [local storage items](https://github.com/IsThereAnyDeal/AugmentedSteam/blob/develop/src/js/Content/Modules/Widgets/AugmentedSteam/Components/LoginWarning.svelte#L24-L26) that stop it from showing on future page loads, meaning it would show up again immediately after reloading or navigating to another page.

Fix login warning not respecting "Don't show again" button

---

src/js/Content/Features/Store/Cart/FCartHistoryLink.ts

Fixes this issue - https://github.com/IsThereAnyDeal/AugmentedSteam/issues/2167
Explanation: an additional `div` was added to `[data-featuretarget="react-root"]` element on Steam page
<details>
<summary>Old react-root</summary>
<div>
</div>
</details>
<details>
<summary>New react-root</summary>
<div>
</div>
</details>

Fix cart history link placement
