js/common.js, js/store.js
NB: This refactors DynamicStore.promise().then() to DynamicStore.then()
=> DynamicStore improvements

options.html
=> one more typo/mistake fixed

js/common.js
Reported by a steam community user on the steam community announcement.
=> Fixes "Number of times this game has been in a bundle" link

js/common.js
This clears up all the uncaught rejections when you aren't logged in.
=> Added early returns from resolved Promises

localization/nl/strings.json
Updated the string "**updated**", replaced "**vernieuwd**" with "**bijgewerkt**".
=> Update of NL Localization

js/store.js
An example: <https://store.steampowered.com/app/1300/SiN_Episodes_Emergence/>
=> Some store pages don't have any videos.

js/common.js
Pages without a header to put the progress bar shouldn't try to add a progress bar
=> URLs without the steam header threw

js/community.js
".badge_empty_name" is only present if are level 0 of the badge
=> Badge page threw if you had a completed badge level

js/store.js
Resolves tfedor/Enhanced_Steam#33
=> Add missing class to fullscreen_button

options.html
original extension, this extension's page, and discord links
=> Add links on the About page

js/store.js
Resolves tfedor/Enhanced_Steam#42
=> Move the "collection" banner out of the way of the price comparison

js/common.js, js/community.js, localization/en/strings.json, options.html
(Mostly) complete fix for tfedor/Enhanced_Steam#54
=>  Add option for, and default to hiding "All friends that own"

js/store.js
=> Fix regional currency not showing in price comparison

js/common.js, js/community.js, js/options.js, js/store.js
Removed the second argument of all calls to `SyncedStorage.get` and added the missing defaults to `Defaults` (except for `homepage_tab_last`)
See #64
=> Refactored SyncedStorage.get

background.html, js/background.js, js/common.js, js/community.js, js/store.js
Continuing work on tfedor/Enhanced_Steam#62
=> Migrate all CORS requests from content context to background context

css/options.css, js/community.js, js/options.js, options.html
Resolves tfedor/Enhanced_Steam#86
=> Toggle quick sale price customization option

js/community.js
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch#The_exception_identifier
=> Regression that prevented community.js from parsing before FF58

js/community.js
Resolves tfedor/Enhanced_Steam#91
=> Check for twitch.tv links in the Text Showcase

js/store.js
For better understanding of what these two values mean
=> Add hyphen between owner numbers of the game

js/community.js
If you quickly scan through your sell listings, you'll get a 429 (Too Many Requests), but there's nothing we can do against that (except maybe setting a timer based on the `Retry-After` header) 
Fixes #98
=> Fix "Lowest price doesn't update when changing sites"

localization/zh-TW/strings.json
Some "Enhanced Steam" were reintroduced by #101
=> Fix #72 reintroduced by #101 in zh-TW localization

js/content/common.js, js/content/store.js
All currently known sections on the front page now have fixed keys and should be consistent when changing languages.
If a new section gets added it is treated like before (localized key) and prints a warning message in the console
See #141
=> Fix front page default customization

js/content/store.js, js/core.js, localization/en/strings.json, options.html
=> Add option to hide wishlist notes on wishlist page

js/content/common.js, js/content/community.js, js/content/store.js
The code was querying the selector on the `document` instead of the `node`.
Also removed redundant calls to `document.querySelector(selector)` in calls to `HTML` functions
=> Fix lowest price

js/content/common.js, js/content/community.js, js/content/store.js, js/core.js
=> Fixes for CSS injected with DOMPurify

js/content/store.js
This is a reappearance of the bug that necessitated tfedor/AugmentedSteam#45
=> Reinstall hover event handlers after sanitization

css/enhancedsteam.css, js/content/store.js
=> Automatically adjust <textarea> width

js/content/store.js
After the renaming of the properties of the currencie's `format`, `currency.format.right` was `undefined`
=> Steam currency

js/content/store.js
=> change in key registration response

js/content/store.js
Allows user created notes for every media (on wishlist or not)
Also improved UX of the modal dialog
See #174
EDIT: Maybe we should also update the SyncedStorage keys and the localization entries
=> User notes

js/content/community.js, js/core.js, js/options/options.js, options.html
Resolves tfedor/AugmentedSteam#208
=> Reenable options for SteamRepCN as per ES.

js/content/common.js, js/content/community.js, js/content/store.js, js/core.js
Replaced single-statement anonymous function expressions through arrow functions.
Converted strings to functions where possible.
In every other case, replaced old delimiters through backtick delimiters
=> Improve readability of functions that are executed in page context

js/content/community.js
Fixes overlapping and position of achievements stats (previous position overlapped with "Ready to play").
Fixes wrong source for achievement stats (always looked into stats of the user)
Adds achievement stats to "Recently played" page of oneself.
Fixes achievement bars for games that have leaderboards (Fetched HTML layout changed)
=> Achievement stats

js/content/community.js
Limits the amount of calls to the market API to one per second to prevent 429 - Too Many Requests
=> Market lowest price throttle

css/enhancedsteam.css, js/content/store.js, localization/en/strings.json
- Fix showing of default hidden elements (e.g. when a user disabled showing VR games)
- Consistent loading of customizer items (using a timeout on app pages)
- Fix hiding 3rd-party data elements on app pages (SteamSpy, performance survey, steamcharts)
- Make sufficient space for "Customize" button on front page and app pages
=> Customizer

js/content/community.js
=> Fix "Zooming in on badge pages creates a vertical offset between items"

js/core.js
Fixes "Open in Steam Client" link
=> Add steam protocol to allowed protocols

js/background/background.js, js/content/common.js
Replaces "An error occurred in the background context." with the error message and meaningful stacktraces.
=> Extended logging of background errors in the content context.

js/content/community.js
=> Remove offline friends nodes so they don't double up when sorting

js/content/common.js, js/content/store.js
Btw we need to really think about the default wishlist color, guess Steam has every variation of blue somewhere on their pages
=> Highlights addition

js/content/community.js
=> Don't leave inventory items with a "loading" class if they have price data

js/content/common.js, js/content/community.js, js/content/store.js
- Simplifies the cross-context messaging by creating simple-to-use interfaces for both sides
- Adds a listener that will get triggered once DynamicStore has finished loading, thus making it easy to determine the time when to start highlighting
- Unrelated addition of the giant curator capsule on the front page to highlighting
=> Dynamic store callbacks

css/enhancedsteam.css, js/content/community.js
Make SteamRep profile data more notable
EDIT: Reworked:
Horizontal alignment works better with the profile header background, it also provides better space usage.
=> SteamRep profile data

js/content/community.js
Intended to resolve tfedor/AugmentedSteam#244
=>  Count transactions retrieved in market stats

js/content/community.js
Breaks style of the otherwise sharp-cornered elements
=> Revert round borders for elements on activity page

js/content/store.js
=> Fix "Updates and Offers" section for Customizer

js/content/community.js, localization/de/strings.json, localization/en/strings.json
=> Add "Year" zoom control to market listing price history

localization/pt-BR/strings.json
Update pt-BR strings from localization
=> Update pt-BR strings

js/content/common.js
Fixes the quicksell issue for Firefox, see jshackles/Enhanced_Steam#1519.
Full credits go to @KarlCastle
=> Change RequestData interface to Fetch API

css/enhancedsteam.css, js/background/background.js, js/content/common.js, js/content/store.js, localization/en/strings.json
If the user is signed out of steamcommunity.com and tries to access community functions, a warning in the same manner of the language warning is displayed on the page
=> Handle community login state

js/content/common.js
=> Fix skipping external confirmation

js/content/community.js
=> community.js: SteamDb -> SteamDB

js/options/options.js
=> Fix not removing old regional price comparison entries on reset

js/content/store.js
- Removes trademark and similar symbols
- Adds keyword "PC" to the query
- Adds filter `intitle` for better results
=> Improve YT search query

js/content/common.js
=> Replace account name on purchase history page

js/content/store.js
=> Fix "Add selected DLC to cart" button

js/content/community.js
Not just the first one.
Fixes #354
=> Apply profile theme to every showcase

js/content/common.js, js/content/community.js, js/content/store.js, localization/en/strings.json
=> Fix different style of achievement bars on "All games" page

js/content/store.js
As a side effect should also fix #330
=> Dynamically adjust wishlist entries' position when popping up price data

js/content/community.js
=> Allow achievement sorting for all languages

options.html
This updated link contains the old and new contributors. The rest of the page might need an update too.
=> Updated contributors link

js/content/community.js
=> Bugfix webchat

js/content/store.js
Resolves https://github.com/tfedor/AugmentedSteam/issues/412
=> Localized accountspend link

README.md, js/content/common.js
Replaced old project links with new ones
=> Updated old project links

js/options/options.js
Fixes https://github.com/tfedor/AugmentedSteam/issues/208
=> Bugfix SteamRepCN visibility

.gitignore
Seems to be generated when the extension crashes/reloads sometimes
=> Added debug.log to gitignore

js/content/community.js, localization/en/strings.json, localization/nl/strings.json
Resolves https://github.com/tfedor/AugmentedSteam/issues/391
=> Added favorite emoticons

js/options/options.js, options.html
=> Added translation percentages

css/enhancedsteam.css, js/content/common.js
Resolves https://github.com/tfedor/AugmentedSteam/issues/415 and resolves https://github.com/tfedor/AugmentedSteam/issues/389
=> Bugfix communityname document title & tooltip

js/content/community.js
Resolves https://github.com/tfedor/AugmentedSteam/issues/391
=> Improved performance of favorite emoticons

css/enhancedsteam.css
Resolves https://github.com/tfedor/AugmentedSteam/issues/397
=> Fix long-shaped artwork thumbnails

js/content/community.js
Original idea from https://greasyfork.org/en/scripts/24714.
=> Added full stats descriptions

js/content/common.js
Resolves https://github.com/tfedor/AugmentedSteam/issues/424
=> Added media scrolling

js/content/community.js
=> Fix regex to remove unnecessary comma in drop-down menu (#460)

css/enhancedsteam.css
Fixes https://github.com/tfedor/AugmentedSteam/issues/497
=> Fixes note cutoff bug

localization/bg/strings.json
Updated according to changes up to "Add Acknowledgments section to credits" in English localization file.
=> [bg] Localization update

js/content/store.js
Should fix https://github.com/tfedor/AugmentedSteam/pull/498#issuecomment-526948380
=> Bugfix search term

js/content/common.js, js/content/community.js, localization/en/strings.json, localization/nl/strings.json
Logs and counts errors + skips unneeded workshop items, as requested by @tfedor
=> Extended workshop subscriber

js/content/community.js
Resolves https://github.com/tfedor/AugmentedSteam/issues/267
=> Added workshop sorting state

js/content/community.js, localization/en/strings.json, options.html
=> improve and add localizations

js/content/store.js
=> Move wishlist ITAD info to bottom of entries

css/enhancedsteam.css, js/content/store.js
Resolves https://github.com/tfedor/AugmentedSteam/issues/579
=> Bugfix reviews font

localization/zh-CN/strings.json
also changed '……' back to '...' to look better
=> Update zh-CN text

js/content/community.js, localization/en/strings.json, localization/nl/strings.json
Resolves https://github.com/tfedor/AugmentedSteam/issues/531
=> Added market history cache

localization/pt-BR/strings.json
=> Update pt-BR localization

css/enhancedsteam.css
Fix #629
Curator page to test the issue:
https://store.steampowered.com/curator/33855818-Nyanco-Channel/
The issue seems to lie with early access items, so check their featured lists for those. Might need to refresh a couple of times.
=> fix curator list bug

css/enhancedsteam.css
Resolves https://github.com/tfedor/AugmentedSteam/issues/545
=> Lowered min-height for artwork

js/content/store.js, localization/en/strings.json
Alternative to #598, see https://github.com/tfedor/AugmentedSteam/pull/598#issuecomment-553681290.
Also added an option for Greenlight banners.
=> Fix and improve apppage customizer

js/content/store.js
1. Fix missing footer when youtube reviews is disabled and broken review links.
2. Simplify the code a bit.
=> Fix and simplify opencritic reviews section

js/options/options.js, localization/en/strings.json, localization/nl/strings.json, options.html
Resolves https://github.com/tfedor/AugmentedSteam/issues/474
=> Remove regional price buttons

css/enhancedsteam.css, js/content/common.js, js/core.js, localization/en/strings.json, localization/nl/strings.json, options.html
Resolves https://github.com/tfedor/AugmentedSteam/issues/448
=> Added back to top button

js/content/common.js, js/core.js, localization/en/strings.json, localization/nl/strings.json, options.html
Resolves https://github.com/tfedor/AugmentedSteam/issues/507
=> Added default community tab

css/enhancedsteam.css, js/content/common.js
Resolves https://github.com/tfedor/AugmentedSteam/issues/658
=> Bugfix scroll to top button placement

css/enhancedsteam.css
It just looks nicer. It's that simple.
=> Added shadow to back to top button

js/background/background.js, js/core.js
Fixes https://github.com/tfedor/AugmentedSteam/issues/649
=> Fixed context menu startup issue

js/content/community.js
=> Fix missing custom theme options

css/enhancedsteam.css, js/content/store.js
Add the required CSS styles for achievement bars to our own CSS file, so hopefully there'll be no need to inject the whole file from Steam.
=> Add achievement bar css styles

css/enhancedsteam.css, js/content/store.js
hltb section: also commented out the remaining suggest link since it doesn't work
wsgf section: also removed the links from rating images since they're all the same as the view ratings link
=> Simplify hltb & wsgf sections

localization/nl/strings.json
Used script from https://github.com/tfedor/AugmentedSteam/pull/608
=> [NL] Updated localization

css/enhancedsteam.css, js/content/store.js
Made css classes more specific. This avoid any bugs on steam pages that may use the same classes.
(Original: https://github.com/tfedor/AugmentedSteam/pull/630)
=> Improved bugfix reviews font

js/content/store.js
Resolves #671 
Used existing code from addTitleHighlight()
=> Highlight top games on stats page

js/content/store.js
Currently nothing gets highlighted on your own wishlist, but I believe it is still useful for cases other than owned/wishlisted.
~~Also replaced the isMyWishlist() function with the one below: I think testing if avatars match is a cleaner solution.~~ Reverted. This method won't work if both profiles have not set custom avatars, or happen to use the same official avatar from the same game.
=> Improve wishlist highlighting

js/content/common.js
=> Fix selector in addTag

css/enhancedsteam.css, js/content/common.js
=> Add highlighting and tagging to header capsules

css/enhancedsteam.css, js/content/community.js
Move styles to css and simplify the code a bit.
=> Simplify CommunityCommon

css/enhancedsteam.css, js/content/community.js
1. Handle applyLinkButtonsLayout() in CSS.
2. Add node checks to prevent errors on past sale event cards e.g. https://steamcommunity.com/my/gamecards/991980
=> Simplify GameCardPageClass

js/content/common.js
Bundle purchase prices was missing because `this.appName` was undefined
=> Simplify Prices, fix bundle purchase price not showing

css/enhancedsteam.css, js/content/store.js
Simplified the code a bit and combined CSS styles.
=> Simplify addDlcInfo, addDlcCheckboxes

js/content/common.js, js/content/community.js
=> Check errorCode message for HTTP 429 Too Many Requests

css/enhancedsteam.css, js/content/store.js
Also
1. Improved isVideo() check: apart from `streamingvideo`, there's also `streamingvideoseries`, `streaming360video`, `series_seasons`
https://store.steampowered.com/app/855130/UnrealMAX_Curso_de_Gamedev/
https://store.steampowered.com/app/1056890/Vienna__Sphaeres_VR_Travel__360_Video__8K2D/
https://store.steampowered.com/app/1072810/The_Princess_the_Stray_Cat_and_Matters_of_the_Heart/
2. Renamed the css class `miniprofile_arrow right` and restored css styles (Valve removed the related styles from shared_global.css after switching to the new miniprofile hover look)
=> Simplify StorePageClass

js/content/community.js
The subscribe feature only works if user is logged in, so add some checks to prevent uncaught errors on for example https://steamcommunity.com/workshop/browse/?appid=221380
Also fixed total item count, see https://github.com/tfedor/AugmentedSteam/pull/722#issuecomment-582896957
=> Add check to addSubscriberButtons and fix item count

js/content/store.js
Bundle pages work the same way as sub pages. Page for testing: https://store.steampowered.com/bundle/11383/Faeria_Game__All_DLC_Bundle/
=> Detect other DRM on bundle pages too

js/background/background.js
Mistake was made @ https://github.com/tfedor/AugmentedSteam/commit/791ec3edb671dd89ade8222487bc355c3f870aea#diff-dc82e5edfbd9fdb7620613e1a528047aL1085
=> Bugfix keys[i] -> key

js/content/community.js, js/content/store.js
Test URL: https://steamcommunity.com/public/notfound
=> Prevent crash on nginx error

js/content/community.js
Fixes https://github.com/tfedor/AugmentedSteam/issues/788
=> Bugfix wrong wishlist count

js/options/options.js, localization/en/strings.json, options.html
Let me know if you want something different.
=> Replaced github link with poeditor

css/enhancedsteam.css, js/content/community.js
The header text alignment issue was reported on AS's chrome store support section.
=> Fix some badges page issues

js/content/store.js
Valve is starting to give soundtracks their own app page. We don't have any special handling for these yet so this simply updates the isDlc() check.
=> Improve isDlc() check

js/content/community.js, localization/en/strings.json, options.html
Also moved and renamed the "Profile links image" option to better reflect its purpose.
=> Simplify GroupHomePageClass

js/content/common.js, localization/en/strings.json, localization/zh-TW/strings.json
So it also works on pages like https://store.steampowered.com/explore/upcoming/
=> Move horizontalScrolling to common functions

js/background/background.js
It wasn't working properly. It _should_ be fixed now. I also did some reformatting
=> Bugfix & reformat context menu

js/content/common.js
=> Make skipGotSteam() modify all links on the page

js/content/store.js
=> Handle the "Install Steam" button on owned apps

js/content/community.js, js/content/store.js
See https://github.com/tfedor/AugmentedSteam/pull/785#issuecomment-595281673
=> Check for the global header to prevent errors

js/content/store.js
Fixes https://github.com/tfedor/AugmentedSteam/issues/835
=> Keep order when exporting wishlist

localization/en/strings.json
Still used, see https://github.com/tfedor/AugmentedSteam/issues/504#issuecomment-602951822
=> Restore localization key hide

js/background/background.js, js/content/community.js
Closes #471
Might be overkill...but it would be nice if this actually works for everyone.
=> Improve wishlist count

js/content/common.js
Also prevents the button from being clickable when it's not visible (opacity = 0).
=> Simplify addBackToTop()

css/enhancedsteam.css, js/content/store.js
Follow-up to https://github.com/tfedor/AugmentedSteam/commit/4d50f6bda34d9b00f92886df0a1de5480f9f0906
=> Fix expand slider not working for YT tabs

js/content/store.js
Resolves tfedor/AugmentedSteam#888
=> Filter chars from keys that are going to Steam

js/background/background.js, js/core.js, js/options/options.js
The base code for this was first implemented in #585, but I thought it was best to make a separate PR for it.
The contextMenus logic was also adapted here, which serves as an example of how it would be used.
=> Implement logic for requesting / removing optional permissions

src/js/Content/Features/Store/Common/FAlternativeLinuxIcon.js
=> Fix alternative linux icon hover style

src/js/Content/Features/Store/App/FShowCoupon.js, src/js/Content/Features/Store/Common/FCustomizer.js
=> Minor improvements to FShowCoupon

src/css/augmentedsteam.css
Most are related to the old wishlist, groups page etc. and other features that ES has already removed, or the user notes, wishlist stats features etc. that AS has implemented in a different way.
=> Remove unused css styles

src/js/Content/Features/Store/App/FPackBreakdown.js
Related https://github.com/tfedor/AugmentedSteam/pull/802#discussion_r407738491
=> Simplify parsing prices in addPackBreakdown

src/js/Content/Modules/AugmentedSteam.js
Make the selector for disableLinkFilter() less specific, so it also works for e.g. links in the "Review" section on app pages.
=> Improve disableLinkFilter()

src/js/Background/Modules/SteamCommunityApi.js
This missing import is breaking new login operations.
=> Fix missing import in SteamCommunityApi

src/js/Content/Features/Community/Inventory/FInventoryMarketHelper.js
Fixup 1b0ff3235bdac18fb692b5a1fe34786635b900cd
=> Fix duplicate button, stray character in Inventory

src/css/augmentedsteam.css, src/js/Content/Features/Store/App/FRemoveFromWishlist.js, src/js/Content/Modules/SteamFacade.js
Mainly tweaked the remove icon to not display when hovering over the temp notice.
=> Minor improvements to FRemoveFromWishlist

src/css/augmentedsteam.css, src/js/Content/Features/Community/Badges/FBadgeCompletionCost.js, src/js/Content/Features/Community/Badges/FBadgeSortAndFilter.js
No actual code changes except moving inline styles to our CSS file and adding labels.
Also made the margins for `popup_menu_item` consistent for all dropdowns (by copying over the styles for `.badge_sort_option`).
=> Simplify badges page CSS styles

src/js/Content/Modules/RequestData.js
Convert to async/await and simplify setting default options.
=> Simplify RequestData

src/js/Content/Features/Store/Common/FAlternativeLinuxIcon.js
fixup #965: only apply the style fixes on storefront; simplify imports
=> Fixup FAlternativeLinuxIcon

src/css/augmentedsteam.css, src/js/Content/Features/Community/ProfileHome/CProfileHome.js, src/js/Content/Features/Community/ProfileHome/FCustomBackground.js, src/js/Content/Features/Community/ProfileHome/FCustomStyle.js, src/js/Content/Features/Community/ProfileHome/FInGameStoreLink.js, src/js/Content/Features/Community/ProfileHome/FProfileDropdownOptions.js, src/js/Content/Features/Community/ProfileHome/FSteamRep.js, src/js/Content/Features/Community/ProfileHome/FSupporterBadges.js, src/js/Content/Features/Community/ProfileHome/FWishlistProfileLink.js
Mainly simplified the check for private profiles, and removed an extra slash in the wishlist link.
=> Simplify some CProfileHome features, fix malformed wishlist link

src/js/Content/Features/Community/ProfileHome/FCustomBackground.js
Removed some inserted HTML for setting profile backgrounds I couldn't find anymore on current profiles.
Also fixed #1016.
Needs testing in case I missed something.
=> Simplify setting profile background and fix issue with background preview

src/js/Content/Features/Community/Groups/FGroupsManageButton.js, src/js/Content/Features/Community/Inventory/FInventoryMarketHelper.js, src/js/Content/Features/Community/WorkshopBrowse/FWorkshopSubscriberButtons.js
I think these are left-overs from the previous implementation which used XHR?
=> Remove invalid fetch request option

src/js/Content/Features/Common/FSkipAgecheck.js, src/js/Content/Features/Community/App/CApp.js, src/js/Content/Features/Community/SharedFiles/CSharedFiles.js
Fixes https://github.com/tfedor/AugmentedSteam/issues/945#issuecomment-759723849.
=> Simplify FSkipAgecheck and add to CSharedFiles

src/css/augmentedsteam.css, src/js/Content/Features/Community/Inventory/FInventoryMarketHelper.js, src/js/Content/Modules/User.js
=> FInventoryMarketHelper: Fix set background option

src/js/Content/Features/Community/MarketListing/FPriceHistoryZoomControl.js, src/js/Content/Features/Community/MarketListing/FSoldAmountLastDay.js
Prevents errors if there was an error loading the market listing or if the item doesn't exist (not marketable)
=> Add prerequisite checks for some CMarketListing features

src/css/augmentedsteam.css, src/js/Content/Features/Store/App/FWidescreenCertification.js
1. Use CSS to layout icons, remove usage of the deprecated `<center>` tag
2. Show icons for "Incomplete" state (we have the icon anyway, might as well show it).
=> Rework WSGF section layout

src/js/Content/Features/Store/Wishlist/CWishlist.js
Triggers a re-calculation of row heights to accommodate the added "UserNotes" area
=> Dispatch resize event after applying features on wishlist

src/css/augmentedsteam.css, src/js/Content/Features/Community/Games/FGamelistAchievements.js, src/js/Content/Modules/Stats.js
This resolves the best part of #997. The rest can be done later if someone raises a feature request I guess.
=> Improve achievement bar display on game list

src/js/Content/Features/Community/Inventory/FInventoryMarketHelper.js
1. For marketable items in own inventory, only add the average price of three cards to booster packs, since lowest price and sold volume is already handled by Steam.
2. Use Steam's method to format avg. cards price display (same issue as quicksell links mentioned in #1044).
3. Add some checks to prevent fetching data more than once; cleanp html a bit.
=> FInventoryMarketHelper: Simplify showing market overview

src/js/Content/Features/Community/Recommended/FReviewSort.js
=> Fix undismissable dialog when sorting reviews

src/css/augmentedsteam.css, src/js/Content/Features/Store/App/FReviewToggleButton.js
Add tooltips to the button and cleanup the code a bit.
=> Improve FReviewToggleButton

src/css/augmentedsteam.css, src/js/Content/Features/Store/App/FWaitlistDropdown.js
Fix dropdown display due to Steam changes described in #1085.
=> Fix add-to-waitlist dropdown menu

src/js/Content/Features/Community/Inventory/FInventoryMarketHelper.js
Improves reliability and makes the feature more self-documenting.
=> Build market link manually in quicksell options

src/js/Content/Features/Store/App/FRemoveFromWishlist.js, src/js/Content/Modules/SteamFacade.js
Remove unreachable code since Steam changes described in #1085.
=> FRemoveFromWishlist: remove dead code

src/js/Content/Features/Community/Badges/FBadgeCalculations.js
Avoid replacing the "How to earn drops?" link, since it contains useful info.
=> Improve badges drop worth display

src/css/augmentedsteam.css, src/js/Content/Features/Community/Badges/CBadges.js, src/js/Content/Features/Community/Badges/FBadgeCalculations.js, src/js/Content/Features/Community/Badges/FBadgeSortAndFilter.js
1. Code cleanup for maintainability and readability, simplify inserting HTML
2. Hide the popup when selecting a view option
3. Only show filter options on own profile
=> Simplify FBadgeSortAndFilter

src/css/augmentedsteam.css
...also re-grouped and fixed the label for related styles while at it.
=> Improve comments for CSS styles that fix an issue

src/css/augmentedsteam.css, src/js/Content/Features/Community/Inventory/FInventoryMarketHelper.js
...also tweaked some text colors to match Steam's.
=> FInventoryMarketHelper: Simplify styles for addPriceToGifts()

src/js/Content/Modules/AugmentedSteam.js
oops...forgot to remove it in #1100
=> Fix undefined function

src/html/options.html, src/js/Options/Modules/CustomLinks.js, src/js/Options/options.js
Refactored the `CustomLinks` module to use similar logic as `Region`, also fixed untranslated labels after creating a new link.
=> Refactor CustomLinks

src/js/Content/Features/Store/App/FShowCoupon.js
Implemented showing price in purchase box (refactored from ES), although the regional pricing will still show old info.
=> FShowCoupon: Update price in purchase box

src/css/augmentedsteam.css
Fixes https://github.com/tfedor/AugmentedSteam/issues/1149
=> Uppercase Customizer

src/js/Content/Features/Store/Common/FExtraLinks.js
Fixes #1175 and misc. cleanup.
=> Fix DOMException at `_moveExtraLinks` due to Steam changes

src/js/Content/Features/Store/App/FHowLongToBeat.js
Avoid frequently displaying an HLTB section with "No Data" until the suggestion link is fixed.
=> Don't show HTLB section if there's no data

src/js/Content/Features/Store/App/FBadgeProgress.js
...typically when not logged in to steamcommunity.
=> Prevent empty badge progress block if there's an error fetching data

src/js/Content/Features/Store/Funds/CFunds.js
None of these common features work on Funds pages.
=> Avoid loading common store features on Funds pages

config/manifests/manifest_common.json, src/js/Content/Features/Community/EditGuide/CEditGuide.js
Fixes https://github.com/tfedor/AugmentedSteam/pull/1179#discussion_r650543775.
=> Fix edit guide page features not working on saved guides

src/html/options.html, src/js/Content/Features/Store/Common/FExtraLinks.js, src/js/Core/Storage/SyncedStorage.js, src/js/Options/Modules/CustomLinks.js, src/js/Options/options.js
Resolves https://github.com/tfedor/AugmentedSteam/issues/1160
Resolves https://github.com/tfedor/AugmentedSteam/issues/1136
=> Added Custom Extra Links

src/html/options.html, src/js/Content/Features/Community/ProfileHome/FCustomStyle.js, src/js/Core/Storage/SyncedStorage.js, src/js/Options/Modules/Data/OptionsSetup.js, src/localization/en.json
Resolves https://github.com/tfedor/AugmentedSteam/issues/667
=> Option to disable Custom Theme everywhere

src/js/Content/Features/Community/TradeOffer/CTradeOffer.js, src/js/Content/Features/Community/TradeOffer/FMyTradeOffersLink.js, src/localization/en.json
I was unable to test this, due to another unrelated error on the tradeoffer page: https://github.com/tfedor/AugmentedSteam/issues/1198
Resolves https://github.com/tfedor/AugmentedSteam/issues/1141
Fixes #1198
=> Added my tradeoffers link

src/js/Content/Features/Community/Badges/FBadgeCalculations.js
Code cleanup, no behavioral changes.
=> Simplify FBadgeCalculations

src/js/Content/Modules/User.js
Alternative of https://github.com/tfedor/AugmentedSteam/pull/1161
=> Fix getting webapi_token

src/js/Background/Modules/SteamCommunityApi.js
Resolves #1213 
Tested and works.
=> Removed paramter and fixed wrong param. usage

src/css/augmentedsteam.css
=> Fix expanded view for workshop items

src/js/Content/Features/Community/Badges/CBadges.js, src/js/Content/Features/Community/Badges/FBadgeSortAndFilter.js, src/js/Content/Modules/SteamFacade.js
Should work now, but I don't have that many badges so I couldn't test the case with multiple pages.
=> Fix image lazy loader on badges page

src/js/Content/Features/Store/App/CApp.js, src/js/Content/Features/Store/App/FDemoAbovePurchase.js, src/js/Content/Features/Store/App/FFamilySharingNotice.js, src/localization/en.json
Closes #1153.
Tested with https://store.steampowered.com/app/289070/Sid_Meiers_Civilization_VI/ and with "Skip the "Got Steam?" window" enabled/disabled.
=> Improve demo link position on app pages

src/js/Content/Features/Store/Wishlist/CWishlist.js, src/js/Content/Features/Store/Wishlist/FWishlistUserNotes.js
=> Fix wishlist rows overlapping on initial load

src/js/Content/Features/Store/App/FReplaceDevPubLinks.js, src/js/Content/Features/Store/App/FSupportInfo.js
=> Fix devpub link replacement and support info position on app pages

src/js/Content/Features/Community/App/CApp.js
I broke this a while ago without realizing, oops...
=> Fix community guides page features

src/js/Content/Features/Community/ProfileEdit/FStyleSelection.js, src/js/Content/Features/Community/ProfileHome/FCustomStyle.js
Closes #794.
Tested manually and seems to work fine.
=> Add 2 past holiday themes

config/manifests/manifest_common.json
my/reviews is accessible by clicking
It seems functionally identical to my/recommended.
=> Add CRecommended match patterns

src/html/options.html, src/js/Options/Modules/Data/OptionsSetup.js
=> Restore "context_steam_market" context menu option

src/js/Content/Features/Community/ProfileHome/FProfileDropdownOptions.js
=> Show current nickname in the input box when adding nicknames

src/css/augmentedsteam.css, src/js/Content/Features/Store/App/FUserNotes.js, src/js/Content/Features/Store/Common/UserNotes.js, src/js/Content/Features/Store/Wishlist/FWishlistUserNotes.js
=> User Notes: simplify state handling, insert note content as plain text, add restore functionality

src/js/Content/Features/Community/FriendsAndGroups/CFriendsAndGroups.js
fixup https://github.com/IsThereAnyDeal/AugmentedSteam/commit/4fd2a05430a953638679ae86606fad7e8ff10801
=> Ensure the search bar on groups page is moved on page load as well

src/js/Content/Features/Store/App/FDemoAbovePurchase.js, src/js/Content/Modules/AugmentedSteam.js
I _think_ it's easier to understand and looks less sketchy if done this way.
=> Replace `ShowGotSteamModal` function instead of setting `href` properties

src/js/Content/Features/Community/GameCard/CGameCard.js, src/js/Content/Features/Community/GameCard/FCardExtraLinks.js, src/js/Content/Features/Community/Games/FCommonGames.js, src/js/Content/Features/Community/Guides/FRemoveGuidesLangFilter.js, src/js/Content/Modules/AugmentedSteam.js
...instead of string manipulation and matching.
=> Use the URL API when working with URLs

src/js/Content/Features/Community/FriendsAndGroups/CFriendsAndGroups.js
I forgot about these pages. The sorting feature is also applicable here.
=> Also apply features after navigating to common friends/groups page

src/css/augmentedsteam.css, src/js/Content/Features/Community/ProfileHome/FViewSteamId.js, src/js/Content/Modules/Clipboard.js
https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText#browser_compatibility
Browser capability is there, but I have no idea how it currently fares in extensions so I kept the old method as a fallback.
=> Prefer the Clipboard API when writing to clipboard

config/manifests/manifest_common.json
You can visit these pages by clicking the "View all x comments" button (made always-visible by AS) under friend activity and status entries.
Reported on Discord: https://discord.com/channels/301903094080339968/568744564261781504/923898387563180052
=> Add more match patterns for profile_activity.js

config/manifests/manifest_common.json, config/webpack/webpack.common.cjs, src/css/augmentedsteam.css, src/js/Content/Features/Community/ProfileHome/FCustomBackground.js, src/js/Content/Features/Store/PointsShop/CPointsShop.js, src/js/Content/Features/Store/PointsShop/FBackgroundPreviewLink.js, src/js/Content/Features/Store/PointsShop/PPointsShop.js, src/js/Content/Modules/Context/ContextType.js
=> Add preview links for profile backgrounds in the points shop

src/js/Content/Features/Store/App/CApp.js, src/js/Content/Features/Store/App/FAStatsLink.js, src/js/Content/Features/Store/App/FAchievementBar.js, src/js/Content/Features/Store/App/FDLCInfo.js, src/js/Content/Features/Store/App/FFamilySharingNotice.js, src/js/Content/Features/Store/App/FHowLongToBeat.js, src/js/Content/Features/Store/App/FMetacriticUserScore.js, src/js/Content/Features/Store/App/FOpenCritic.js, src/js/Content/Features/Store/App/FOwnedElsewhere.js, src/js/Content/Features/Store/App/FRemoveFromWishlist.js, src/js/Content/Features/Store/App/FSteamChart.js, src/js/Content/Features/Store/App/FSteamSpy.js, src/js/Content/Features/Store/App/FSurveyData.js, src/js/Content/Features/Store/App/FWidescreenCertification.js
Finished off a TODO to convert checks into properties, and extended some properties to cover more items. Also simplified some stuff in 3rd-party info features.
=> CApp: fix and improve properties

src/js/Content/Features/Store/Sub/FSavingsCheck.js
Mainly removed the timeout before applying the feature since it doesn't seem necessary now.
This is one of the oldest features provided by ES, and according to https://github.com/jshackles/Enhanced_Steam/commit/ab67a774f32c8d5201b87cc9e28aceda01636a62 this feature should apply to bundles as well, but I can't find any bundle that's missing savings info so it probably doesn't matter now.
=> FSavingsCheck: remove timeout and simplify

src/js/Content/Features/Community/GameCard/CGameCard.js, src/js/Content/Features/Community/GameCard/FCardMarketLinks.js
Refactored some alway-truthy checks to check the actual data instead.
=> FCardMarketLinks: refactor some checks

src/js/Content/Features/Store/App/CApp.js, src/js/Content/Features/Store/App/FHideReportedTags.js, src/js/Core/Html/HtmlParser.js
=> Add feature to hide reported tags on app pages

src/localization/en.json
- Changed "on Price" to "On Price".
- Removed some unnecessary double spaces.
This closes #1414.
=> Update English localization

src/js/Content/Features/Store/Common/CStoreBase.js, src/js/Content/Features/Store/Common/FFocusSearch.js
Closes #1459.
This works but I might be missing some edge case.
=> Add feature to focus search box by pressing "s"

src/js/Content/Features/Store/App/FDemoAbovePurchase.js
Some cleanup to more closely match the implementation of the new "Add to Library" button.
=> Minor cleanup in FDemoAbovePurchase

src/css/augmentedsteam.css, src/js/Content/Features/Community/MarketHome/FMarketLowestPrice.js, src/localization/en.json
1. Better error handling to fix #1448, which is likely due to `Price.parseFromString()` throwing when `data.lowest_price` is `undefined`. Also indicate when price data is loading, when an error occurred, and when data is missing.
2. About TODO comments -- the width changes are indeed necessary to fix spacing due to the additional "game name" header inserted by the sorting feature. But it can probably be removed after #1481.
3. Changed some class names and minor refactoring for clarity. Also limited the number of retries after a timeout to 2. The original code didn't seem to have a limit...
4. Merged market-related CSS styles.
5. This and market sorting needs to be reapplied on page changes, so they should be rewritten as callback features. I'll try working on that later.
=> FMarketLowestPrice: better error handling, minor refactoring

src/css/augmentedsteam.css
Closes #1472, with the changes suggested here https://discord.com/channels/301903094080339968/532283733076869143/907620773181657108
=> Fix achievement progress bar and text display

src/js/Content/Modules/Prices.js
Add voucher discount to total discount in display. Might be better to wait until #1489 is fixed.
=> Fix price cut % with a voucher applied

src/js/Content/Features/Store/Common/UserNotes.js
Fixes #1466.
Also avoids auto-confirming a selection by hitting Enter, which I think is a good thing.
=> Fix notes "OutOfCapacity" dialog might be dismissed unexpectedly

src/css/augmentedsteam.css, src/js/Content/Features/Community/MarketHome/CMarketHome.js, src/js/Content/Features/Community/MarketHome/FMarketLowestPrice.js, src/js/Content/Features/Community/MarketHome/FMarketSort.js
Tie up some loose ends in #1482.
=> Fixup market lowest prices

src/js/Content/Features/Community/MarketHome/FMarketLowestPrice.js
We insert a delay between requests, but it's placed right before `getPriceOverview()` returns, which delays displaying results for the first and last row for no reason. This puts the delay before the request instead, and makes it so there's no additional delay before the first request and after a timeout. Also restored some logic that was removed in #1482 to add better error handling -- if we failed to parse appid or market hash name, show an error instead of being stuck in loading.
=> Move delay between requests to save time

src/js/Content/Features/Store/PointsShop/FBackgroundPreviewLink.js
Also fixes https://github.com/IsThereAnyDeal/AugmentedSteam/pull/1336#issuecomment-1007925215.
=> Simplify points shop background preview link

src/js/Content/Features/Common/CBase.js
Fixup https://github.com/IsThereAnyDeal/AugmentedSteam/commit/6ffaba631e2dfaf82b9d6ad0071ba83bcc0cc47d
=> Fix missing FDefaultCommunityTab feature

src/js/Content/Features/Store/Common/AddToCart.js
=> Avoid free promotions getting added to Cart

src/js/Content/Features/Community/ProfileHome/FCommunityProfileLinks.js, src/js/Content/Features/Store/App/FSupportInfo.js, src/js/Content/Features/Store/Common/FExtraLinks.js, src/js/Core/Html/Html.js
custom 3rd-party sites enable custom protocal
=> fix: 🐛 #1548

src/js/Content/Features/Community/EditGuide/CEditGuide.js, src/js/Content/Features/Community/Guides/CGuides.js, src/js/Content/Features/Community/MyWorkshop/CMyWorkshop.js
None of the base features work here.
=> CEditGuide: don't apply base features

src/js/Content/Features/Community/Badges/FBadgeSortAndFilter.js, src/localization/en.json
=> Add the ability to sort badges by least cards remaining to complete set

src/css/augmentedsteam.css, src/js/Content/Features/Store/Wishlist/CWishlist.js, src/js/Content/Features/Store/Wishlist/FWishlistProfileLink.js
=> Add profile link on wishlists

src/js/Content/Features/Store/App/FHDPlayer.js
Weird things happen when hovering over the new titlebar, but that's not our fault.
=> FHDPlayer: refactor

src/css/augmentedsteam.css, src/js/Content/Modules/AugmentedSteam.js
=> Fix handling the Install Steam button

src/html/options.html, src/js/Content/Modules/UpdateHandler.js, src/js/Core/Storage/SyncedStorage.ts, src/js/Options/Modules/Data/OptionsSetup.js, src/localization/en.json
Forgot to remove this in #1585, whoops!
=> Remove unused option for Games page

src/css/augmentedsteam.css, src/js/Content/Features/Common/FHighlightsTags.js
Also removed `margin-top: -1px` because I couldn't tell the difference.
=> Fix DLC row tags position when discounted

src/css/augmentedsteam.css, src/js/Content/Modules/AugmentedSteam.js
Tweak menu styles to match the account dropdown.
=> Improve menu styles

src/js/Background/Modules/SteamCommunityApi.js, src/js/Content/Features/Common/FHighlightsTags.js, src/js/Content/Modules/Data/Inventory.js, src/js/Content/Modules/ITAD.js
Clean up `getAppStatus()` methods to use similar logic as DynamicStore (#1643).
=> Refactor `getAppStatus()` methods

src/js/Background/Modules/SteamStoreApi.js, src/js/Content/Modules/CurrencyManager.js
`g_rgWalletInfo` can be parsed from the page script, also simplified the logic a bit.
=> Simplify getting store currency

src/js/Content/Features/Community/ProfileEdit/FBackgroundSelection.js, src/js/Core/Utils/StringUtils.js
Resolves https://github.com/IsThereAnyDeal/AugmentedSteam/pull/1626#issuecomment-1546893793.
Most of the logic is copied from Steam's `CGameSelectorOwnedGames`.
=> Improve matched results while searching for custom backgrounds

src/js/Content/Features/Community/MarketHome/FMarketLowestPrice.js
=> Fix error if user has no active listings

config/webpack/Plugins/ManifestTransformerPlugin.cjs
Noticed these issues when working on other stuff, figured I'll get these in first.
=> Improve manifest transform

src/js/Content/Features/Common/FHighlightsTags.js, src/js/Content/Features/Store/App/FSteamPeek.js, src/js/Content/Modules/AugmentedSteam.js, src/js/Content/Modules/Data/DynamicStore.js, src/js/Content/Modules/SteamFacade.js
Closes #1645.
There's still the problem where highlights aren't "dynamic", and requires a reload to fix.
=> Create global handlers for DS methods

src/js/Content/Features/Community/FHideSpamComments.js
Broke this a while ago without realizing 😐
=> Fix hide spam comments feature

src/js/Background/Modules/Api.js, src/js/Background/Modules/SteamCommunityApi.js, src/js/Content/Features/Store/Common/FAddToCartNoRedirect.js
=> Fix undefined variable

src/css/augmentedsteam.css, src/js/Content/Features/Community/App/FCommunityAppPageWishlist.js
=> FCommunityAppPageWishlist: create a common parent for wishlist buttons

src/js/Content/Features/Store/Common/FAddToCartNoRedirect.js
=> Fix feature hint event handling

src/js/Content/Features/Common/FSkipAgecheck.js
Steam changed this a while ago.
=> Fix skipping community content warnings

src/js/Core/Storage/SyncedStorage.ts
=> Fix undefined property on SyncedStorage instance

src/js/Content/Features/Store/Common/UserNotes.js, src/js/Core/Storage/UserNotesAdapter.js
Closes #1634, and fixed some bugs along the way.
=> Per-game notes autosave

src/js/Options/options.js
=> Add temp check before processing imported settings

src/js/Content/Features/Community/Badges/CBadges.js
Fixes #1710.
There're still some bugs with the filter feature that'll be fixed later.
=> Fix fetching badges when sorting by "A-Z"

src/js/Content/Features/Community/ProfileStats/CProfileStats.js, src/js/Content/Features/Community/ProfileStats/FShowHiddenAchievements.js
=> Unbreak show hidden achievements feature

src/css/options.css
<details><summary>Before:</summary>
</details>
<details><summary>After:</summary>
</details>
=> Make dark scroll bar in Chromium-based browsers

src/js/Content/Features/Community/ProfileEdit/CProfileEdit.js, src/js/Content/Features/Community/ProfileEdit/FBackgroundSelection.js, src/js/Content/Features/Community/ProfileEdit/FStyleSelection.js
These two features work in similar ways and should be merged somehow; we only need one observer 🤔
Fixes #1849
=> Fix profile edit page features not showing up

src/js/Content/Features/Community/ProfileStats/CProfileStats.js, src/js/Content/Features/Community/ProfileStats/FShowHiddenAchievements.js
Moved fetching achievements local to the feature, also disabled achievement sort since it's broken at the moment, refs #1798.
=> Tweaks to FShowHiddenAchievements, disable FAchievementSort

src/js/Content/Modules/Prices/PriceOverview.svelte
=> Fix prices component height on wishlists

src/js/Content/Features/Community/ProfileStats/FAchievementSort.ts
Achievements unlocked in the current year don't show the year in the unlock time.
Fixes #1890
=> Fix achievement sorting when dates have no year

src/js/Content/Features/Store/App/FPlayers.svelte
Forgot to add this option back in #1858 😅
=> Fix FPlayers option

src/js/Background/Modules/SteamCommunityApi.js
Didn't test this, just ported the original logic from ES and simplified a bit.
Fixes #1779.
=> Fix detecting inventory gifts

src/js/Content/Features/Store/PointsShop/FBackgroundPreviewLink.js
Since Steam mangled the class names, find if a background item is clicked by looping over all `div` elements and check for the mockup profile background image. Not pretty, but it works...
=> Fix background preview links for the nth time

src/js/Background/Modules/Api.js, src/js/Background/Modules/SteamCommunityApi.js, src/js/Background/Modules/SteamStoreApi.js
Revert #1648 since it no longer works.
Related to #1760.
=> Remove login flow workaround

src/js/Content/Features/Store/Wishlist/FExportWishlist.js
Steam finally fixed this a few days ago 🙄
=> Remove export wishlist dialog CSS fix

src/js/Background/Modules/SteamStoreApi.js, src/js/Content/Features/Common/FHighlightsTags.js, src/js/Content/Modules/Data/DynamicStore.js
Supplement to f3e0f799cfd75a5e81db4a5ef2652ff392036a4c
=> Shorten some property and function names too

src/js/Background/Modules/AugmentedSteam/AugmentedSteamApi.ts
=> Fix fetching profile data

src/js/Content/Features/Store/App/FFamilySharingNotice.svelte, src/js/Content/Features/Store/App/FFamilySharingNotice.ts
=> FFamilySharingNotice: fix condition and svelte-fy

src/js/Content/Modules/Widgets/SortBox.svelte
Not quite sure about this, but it works. Seems like it'll be easier to handle in svelte 5.
=> Fix Sortbox not triggering change for initial option

src/js/Content/Features/Store/Common/FITADPrices.ts
I think I tried changing this a while back, but I forgot why it wasn't done like this in the first place. There might be edge cases but initial tests look fine.
The "Steam family owns this game" banner is in the same position as the "Buy this game as a gift" text, so I think it should be kept where it is, but we can probably add a separater so it looks nicer.
Fixes #1911.
=> Simplify inserting ITAD prices

src/js/Content/Features/Store/Common/FDRMWarnings.ts
=> Fix drm warnings

src/js/Content/Features/Community/FriendsAndGroups/FGroupsSort.ts
=> Fix groups sorting only working on own profile

src/js/Content/Features/Community/Inventory/FShowMarketOverview.ts, src/scriptlets/Community/Badges/loadImages.js, src/scriptlets/Community/FriendsAndGroups/inviteToGroup.js, src/scriptlets/Community/Inventory/marketOverviewPopulation.js, src/scriptlets/Community/ProfileActivity/patchBlotter.js
Also fixed the market overview scriptlet since it's broken in the same way.
=> Fix invite to group scriptlet

src/js/Core/GameId/AppId.ts
Steam added this new CDN recently. Also fixed some checks and types.
=> Fix getting appid from new Steam CDN links

src/js/Content/Features/Community/GameCard/CGameCard.ts, src/js/Content/Features/Community/GameCard/FCardMarketLinks.ts
=> Fix cards page badge completion cost styling issues

src/js/Content/Modules/Data/DynamicStore.ts, src/scriptlets/SteamScriptlet.js
See #1944, essentially the dynamicstore scriptlet should be inserted earlier to avoid the promise potentially never resolving. Should be ideal even if the root cause is fixed.
=> Cleanup some scriptlets

src/css/augmentedsteam.css, src/js/Content/Features/Store/Common/FDRMWarnings.svelte, src/js/Content/Features/Store/Common/FDRMWarnings.ts
Svelte-fy and improve maintainability
=> Refactor DRM warnings

src/css/augmentedsteam.css, src/js/Content/Features/Community/Games/FGamesStats.svelte, src/js/Content/Features/Community/Games/FGamesStats.ts
Svelte-fy games page stats and reworked to use a dropdown, same as the licenses page.
=> Refactor games page stats

src/js/Core/GameId/AppId.ts
=> Fixup Steam CDN regex

src/js/Content/Features/Community/Guides/FRemoveGuidesLangFilter.ts
=> FRemoveGuidesLangFilter: fix day select dropdown when filtering by Most Popular

src/js/Content/Modules/Widgets/ProgressBar.svelte, src/js/Core/Background.ts
Turns out this was all that was needed to fix the progressbar animation 😅
=> Await return value from `runtime.sendMessage`

src/js/Content/Features/Community/TradeOffer/CTradeOffer.ts, src/js/Content/Features/Community/TradeOffer/FCountTradeItems.ts, src/js/Content/Features/Community/TradeOffer/FMyTradeOffersLink.ts, src/js/Content/Features/Community/TradeOffer/PTradeOffer.ts
Would be nice to svelte-fy, but it seems more trouble than it's worth 😅
=> Fix CTradeOffer features

src/css/augmentedsteam.css, src/js/Content/Features/Community/ProfileActivity/FToggleComments.ts, src/js/Content/Features/Store/App/FSteamPeek.css, src/js/Content/Features/Store/App/FSteamPeek.ts, src/js/Content/Features/Store/Common/Customizer/Customizer.svelte, src/js/Content/Modules/Prices/PriceOverview.svelte
Mainly moved some styles to component. I'll slowly deal with the rest 😅
=> CSS splitting part1

src/js/Content/Features/Community/ProfileEdit/CProfileEdit.ts, src/js/Content/Features/Community/ProfileEdit/FBackgroundSelection.ts, src/js/Content/Features/Community/ProfileEdit/FStyleSelection.ts
Use a single mutation observer to detect tab changes, and use events to control feature loading, similar to friends and groups page.
=> CProfileEdit: refactor feature loading across tab changes

src/js/Background/Modules/IsThereAnyDeal/ITADApi.ts
=> Fix error when pulled notes are empty

src/js/Content/Features/Store/App/FDLCCheckboxes.css, src/js/Content/Features/Store/App/FDLCCheckboxes.ts
Catching up with Steam changes. As usual I used `https://store.steampowered.com/app/703080/` for testing.
=> Fix styles related to DLC checkboxes
